### ISSUE TITLE
[Feature Request] Upload Android App Bundle, .aab files

### ISSUE THREAD

**Issue by JesperSjoquist** [microsoft/google-play-vsts-extension#100]
There are now API's available for uploading the new Android App Bundle format:
https://developers.google.com/android-publisher/api-ref/edits/bundles/upload

It would be great to have this ability in our CI environment.

**Comment by rramprasad** [comment]
Need to support for Android App Bundle

**Comment by davidvavra** [comment]
+1. It's not really that hard to implement, just detect if AAB file is present after the build and upload it instead of APK

**Comment by gzarkovic-livly** [comment]
We would like to see this as well!

**Comment by ThomasNigro** [comment]
Is there a status update regarding the implementation of this?

**Comment by nate-eisner** [comment]
Over a year later and still nothing on this?

**Comment by MaxGuernseyIII** [comment]
I suppose we could try looking into it ourselves and submit a pull request or something...

**Comment by MaxGuernseyIII** [comment]
Looks like the problem might be in a dependency?

From https://github.com/microsoft/google-play-vsts-extension/blob/master/Tasks/google-play-release/GooglePlay.ts:

`        const reader = await apkReader.open(apkFile);
        const manifest = await reader.readManifest();`

**Comment by SebAubin** [comment]
Is there any updates on this request?

**Comment by MaxGuernseyIII** [comment]
I used fastlane on a hosted mac. I had to use it to promote, too.

**Comment by mamingcao** [comment]
No update? Google will force everyone to use bundle on Aug 1st 2019?

**Comment by mskg** [comment]
Any update on this?

**Comment by dansiegel** [comment]
Would really love to see some traction on this. For that matter @ryuyu would love to know is this task still being supported? It hasn't been touched in 9 months...

**Comment by aloisdeniel** [comment]
We seriously need this!

**Comment by jonsamwell** [comment]
+1!

**Comment by jonsamwell** [comment]
For everyone coming to this I had to use fastlane on a mac os azure agent

```
# See https://docs.fastlane.tools/actions/upload_to_play_store/

fastlane supply --aab $(System.DefaultWorkingDirectory)/_Mobile_App/app.aab --track internal --rollout 1.0 --json_key $(Google_Play_Service_Account_Private_Key.secureFilePath) --package_name com.example.app
```

**Comment by dansiegel** [comment]
@jonsamwell that's great info... thanks... 

@lkillgore can you please provide the community with some idea of when we might expect aab support?

**Comment by sfratini** [comment]
I am actually trying to make this work, however it is not that simple since AAB files are not stored in binary format but in protocol buffers, so the AndroidManifest cannot be easily read. If I make it work, I'll send a PR.

**Comment by andrewleader** [comment]
Wow it's been over a year? I just switched my apps to AAB and the lack of this is really a pain.

**Comment by andrewleader** [comment]
Wahooo!!!! 🚀🎉  @erjohnms do you have a timeframe for when the extension will receive this new update in DevOps?

**Comment by andrewleader** [comment]
@erjohnms any update on when it'll be available on DevOps?

**Comment by darrentaft** [comment]
> @erjohnms any update on when it'll be available on DevOps?

It's already there as a new task named "Google Play - Release Bundle" or task ID "GooglePlayReleaseBundle@3"

**Comment by andrewleader** [comment]
Oh sweet!!! I didn't think to look for a separate task. Thank you @darrentaft !

**Comment by trajano** [comment]
The documentation https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops needs to be updated with this task
