### ISSUE TITLE
internal server error, with no cause in error logs {"cause":{"code":500},"isOperational":true,"code":500}

### ISSUE THREAD

**Issue by premtodkar** [Microsoft/google-play-vsts-extension#102]
Below is the log generated during apk deployment on google play store. Some details are made hidden.

Initializing JWT.
 ##[debug]Initializing Google Play publisher API.
 ##[debug]Authorize JWT.
 Authenticated with Google Play and getting new edit 
##[debug]Creating a new edit transaction in Google Play.
##[debug]Request Parameters: {"packageName":"*****"}
##[debug]Updating Global Parameter editId to "************"
##[debug]   ... updated.
##[debug]Uploading 1 APK(s).
##[debug]Uploading APK **************************
 ##[debug]Request Parameters: {"packageName":"******","media":{"body":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":1,"path":"*******","fd":null,"flags":"r","mode":438,"autoClose":true,"bytesRead":0},"mimeType":"application/vnd.android.package-archive"}}
##[debug]returned: {"versionCode":2109,"binary":{"sha1":"********"}}
##[debug]Uploaded ****** with the version code 2109
Updating track information...
##[debug]Updating the track internal.
 ##[debug]New internal track version codes: [2109]
##[debug]Updating the internal track info.
 ##[debug]Request Parameters: {"packageName":"*******","track":"internal","resource":{"track":"internal","versionCodes":[2109]}}
 ##[debug]Updated track info: {"track":"internal","versionCodes":[2109]}
 ##[debug]Upload the common change log D:\a\r1\a to all versions
 ##[debug]The change log path D:\a\r1\a either does not exist or points to a directory. Ignoring...
##[debug]Committing the edit transaction in Google Play.
 ##[debug]Error in edits.commitAsync(): {"cause":{"code":500},"isOperational":true,"code":500}
 ##[debug]task result: Failed
##[error]Error: Error in edits.commitAsync(): {"cause":{"code":500},"isOperational":true,"code":500}
 ##[debug]Processed: ##vso[task.issue type=error;]Error: Error in edits.commitAsync(): {"cause":{"code":500},"isOperational":true,"code":500}
 ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error in edits.commitAsync(): {"cause":{"code":500},"isOperational":true,"code":500}
 ##[section]Finishing: Release

**Comment by premtodkar** [comment]
@madhurig can you look at this?

**Comment by madhurig** [comment]
Hi,

How did you setup authentication? How do you generate your json authentication file?
When using Service Endpoint authentication method, the credential should come from "SERVICE ACCOUNTS" instead of the "OAUTH CLIENTS" in the Google Play developer console.

Thanks,
Madhuri

**Comment by OndrejKunc** [comment]
Hi,

Same issue here. The apk deployment to the google play store was working fine for about year and a half. 6/11/2018 was last successful attempt and 6/14/2018 I started receiving this error without any change of the task.
I also use service account. I tried to switch from version of the task from 1.* to 2.* but the error is still the same. Manual deployment of the apk to the store works fine.

Thanks,

Ondrej Kunc

**Comment by madhurig** [comment]
@OndrejKunc: Can you please share a successful and failed log? Any update in your app - say target Android version?

**Comment by OndrejKunc** [comment]
@madhurig  I am using Xamarin for this this Android project and only update relevant to the Android projects was adding Xamarin Media Plugin, which references Java.Interop assembly besides other assemblies, but I don't think this is the cause of the problem.
After I start getting this error I also tried to update Android target framework version from 7.1 to 8.1 but it didn't help.
Here is my last successful log (unfortunately without logging debug mode turned on)

```
##[section]Starting: Google play dev alpha release
==============================================================================
Task         : Google Play - Release
Description  : Release an app to the Google Play Store
Version      : 1.129.0
Author       : Microsoft Corporation
Help         : 
==============================================================================
*Some Guid* exists true
Found main APK to upload: e:/TFSBuild-work/r3/a/PathToApp/myapp.apk (version code 20330113)
Authenticated with Google Play and getting new edit 
Updating track information...
APK successfully published!
Track: alpha
##[section]Finishing: Google play dev alpha release
```

And here is the recent log from the 2.* version of the task. Some details are hidden:
```
##[debug]Evaluating condition for step: 'Google play dev alpha release'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> (Boolean) True
##[debug]Expanded: True
##[debug]Result: True
##[section]Starting: Google play dev alpha release
==============================================================================
Task         : Google Play - Release
Description  : Release an app to the Google Play Store
Version      : 2.135.0
Author       : Microsoft Corporation
Help         : 
==============================================================================
##[debug]agent.TempDirectory=e:\TFSBuild-work\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_*Some Guid*
##[debug]loading ENDPOINT_AUTH_PARAMETER_*Some Guid*_PASSWORD
##[debug]loading ENDPOINT_AUTH_PARAMETER_*Some Guid*_USERNAME
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_*Some Guid*
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_APKFILE
##[debug]loading INPUT_AUTHTYPE
##[debug]loading INPUT_CHANGELOGFILE
##[debug]loading INPUT_LANGUAGECODE
##[debug]loading INPUT_METADATAROOTPATH
##[debug]loading INPUT_SERVICEACCOUNTKEY
##[debug]loading INPUT_SERVICEENDPOINT
##[debug]loading INPUT_SHOULDATTACHMETADATA
##[debug]loading INPUT_SHOULDUPLOADAPKS
##[debug]loading INPUT_TRACK
##[debug]loading INPUT_VERSIONCODEFILTERTYPE
##[debug]loaded 18
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]check path : e:\TFSBuild-work\_tasks\GooglePlayRelease_*Some Guid*\2.135.0\task.json
##[debug]set resource file to: e:\TFSBuild-work\_tasks\GooglePlayRelease_*Some Guid*\2.135.0\task.json
##[debug]system.culture=en-US
##[debug]Prepare task inputs.
##[debug]authType=ServiceEndpoint
##[debug]serviceEndpoint=*Some Guid*
*Some Guid* exists true
##[debug]*Some Guid* exists true
##[debug]apkFile=e:\TFSBuild-work\r3\a\PathToApp/myapp.apk
##[debug]Main APK pattern: e:\TFSBuild-work\r3\a\PathToApp/myapp.apk
##[debug]check path : e:/TFSBuild-work/r3/a/PathToApp/myapp.apk
Found main APK to upload: e:/TFSBuild-work/r3/a/PathToApp/myapp.apk (version code 20330259)
##[debug]    Found the main APK file: e:/TFSBuild-work/r3/a/PathToApp/myapp.apk (version code 20330259).
##[debug]additionalApks=null
##[debug]versionCodeFilterType=all
##[debug]track=alpha
##[debug]userFraction=null
##[debug]shouldAttachMetadata=false
##[debug]shouldUploadApks=true
##[debug]changelogFile=e:\TFSBuild-work\r3\a
##[debug]languageCode=en-US
##[debug]Getting a package name from e:/TFSBuild-work/r3/a/PathToApp/myapp.apk
##[debug]Updating Global Parameter packageName to "mypackagename"
##[debug]   ... updated.
##[debug]Initializing JWT.
##[debug]Initializing Google Play publisher API.
##[debug]Authorize JWT.
Authenticated with Google Play and getting new edit 
##[debug]Creating a new edit transaction in Google Play.
##[debug]Request Parameters: {"packageName":"mypackagename"}
##[debug]Updating Global Parameter editId to "*somenumber*"
##[debug]   ... updated.
##[debug]Uploading 1 APK(s).
##[debug]Uploading APK e:/TFSBuild-work/r3/a/PathToApp/myapp.apk
##[debug]Request Parameters: {"packageName":"mypackagename","media":{"body":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":1,"path":"e:/TFSBuild-work/r3/a/PathToApp/myapp.apk","fd":null,"flags":"r","mode":438,"autoClose":true,"bytesRead":0},"mimeType":"application/vnd.android.package-archive"}}
##[debug]returned: {"versionCode":20330259,"binary":{"sha1":"*some hash*","sha256":"*some hash*"}}
##[debug]Uploaded e:/TFSBuild-work/r3/a/PathToApp/myapp.apk with the version code 20330259
Updating track information...
##[debug]Updating the track alpha.
##[debug]New alpha track version codes: [20330259]
##[debug]Updating the alpha track info.
##[debug]Request Parameters: {"packageName":"mypackagename","track":"alpha","resource":{"track":"alpha","versionCodes":[20330259]}}
##[debug]Updated track info: {"track":"alpha","versionCodes":[20330259]}
##[debug]Upload the common change log e:\TFSBuild-work\r3\a to all versions
##[debug]The change log path e:\TFSBuild-work\r3\a either does not exist or points to a directory. Ignoring...
##[debug]Committing the edit transaction in Google Play.
##[debug]Error in edits.commitAsync(): {"cause":{"code":500},"isOperational":true,"code":500}
##[debug]task result: Failed
##[error]Error: Error in edits.commitAsync(): {"cause":{"code":500},"isOperational":true,"code":500}
##[debug]Processed: ##vso[task.issue type=error;]Error: Error in edits.commitAsync(): {"cause":{"code":500},"isOperational":true,"code":500}
##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error in edits.commitAsync(): {"cause":{"code":500},"isOperational":true,"code":500}
##[section]Finishing: Google play dev alpha release
```

**Comment by OndrejKunc** [comment]
Good news. It suddenly started to work without any change from my side.
I looked at the logs for the last failed attempt and for the first successful attempt and there is almost no difference except there is no error in the working one. Both of those attempts have task version of 2.141.0 so I guess something must have changed on the Google Play side.

**Comment by lkillgore** [comment]
Thanks @OndrejKunc  for letting us know!
