### ISSUE TITLE
Failed to upload the APK X.apk. Failed with message: Error: APK is not zip aligned

### ISSUE THREAD

**Issue by ImGonaRot** [Microsoft/google-play-vsts-extension#104]
I'm actually having two problems.

1. 
If I "check" the "Update APK" in the Google Play Release task, the publish will fail with error. "Failed to upload the APK X.apk. Failed with message: Error: APK is not zip aligned"
I already have a task in the build job that does Signing and aligning APK "before" the Google Play Release task.

2. 
If I "un-check" the "Update APK" in the Google Play Release task, the publish will pass BUT I can't find the release on the Google Play Console.
I have posted the VSTS release log in the link below.
Details reported here https://github.com/Microsoft/google-play-vsts-extension/issues/75

**Comment by madhurig** [comment]
@ImGonaRot: Can you share your debug build logs?

For issue 1 with APK not being zip aligned, it might be that the zip aligned APK is not being selected for the upload and accidentally the non-zip aligned APK is being selected for upload. 

For issue 2, unchecking "Update APK" means that only metadata will be uploaded to an existing release that was done previously. I don't think this is what you want.

Thanks,
Madhuri

**Comment by ImGonaRot** [comment]
@madhurig I shared the build log on the like for item #75 
Please let me know if you prefer that I copy the log here.

1.) 
My build already zip aligns the APK. and I can "manually" upload to the Google store right after the VSTS build has finished by going to the artifact folder, download the apk, then upload to Googl store. 
The store accepts the APK, so I know it is definitely zip aligned correctly. 
What I was saying is that if I use the VSTS "Google Play Release" task and check the "Update APK" box, it "alters" the APK and once it is altered, it fails zip align test on the Google store when I upload the file. 
I must be doing something wrong because the "Update APK" check box is killing my apk.
