### ISSUE TITLE
Multiple Closed Alpha Tracks

### ISSUE THREAD

**Issue by mcpummec** [microsoft/google-play-vsts-extension#108]
Please add support for tracks other than [Alpha, Beta, Rollout, Production]. I need to maintain multiple closed alpha tracks!

**Comment by myrjola** [comment]
Would this be as easy as adding `"editableOptions": "True"` for the tracks option in https://github.com/Microsoft/google-play-vsts-extension/blob/master/Tasks/google-play-release/task.json#L68

**Comment by mcpummec** [comment]
At first glance, it seems like this would do the trick for me!

**Comment by erjohnms** [comment]
This feature is now released
