### ISSUE TITLE
How to specify multi language changelog? (en-US;de-DE)

### ISSUE THREAD

**Issue by AndrewBedscastle** [Microsoft/google-play-vsts-extension#109]
Is it possible to update the changelog for multiple language identifiers in one step, eg. en-US and de-DE?
How must the changelog file look like to provide that functionality? How must the input field be filled?

Or is it not yet possible?

Thank you

**Comment by madhurig** [comment]
This extension support uploading changelogs for mulitple languages but you will have to set them up in the format that fastlane supports: https://docs.fastlane.tools/actions/supply/#changelogs-whats-new 

Let us know if you see any issues with that.

Thanks,
Madhuri

**Comment by hammady** [comment]
As madhurig has suggested, use the fastlane supply tool to download your existing metadata from Google Play, then check in those files in your source control. You will find a folder called changelogs, this is where you update your changelogs for all the languages. Once changed, check the option "Update Metadata" and give your metadata path in either the source or the published artifact. In the source case, you must include it as an artifact in your Release pipeline.

**Comment by madhurig** [comment]
Closing the issue. Let us know if you were not able to get this working.
