### ISSUE TITLE
Not getting add option when trying to add in build step

### ISSUE THREAD

**Issue by deec1** [Microsoft/google-play-vsts-extension#110]
I've installed teh plugin from the market place however when I try to add the google play to a build pipline step I can see it int he list, it tells me it is installed but I don;t get an add button.

**Comment by madhurig** [comment]
I am seeing this with another extension as well, not just this one. I will follow up and get back to you. 

Thanks,
Madhuri

**Comment by marius-bughiu** [comment]
I think it got fixed; I now see the tasks in my account.

![image](https://user-images.githubusercontent.com/11870708/48279071-2099b780-e458-11e8-8c82-42769c013ef2.png)

@deec1 can you confirm?

**Comment by madhurig** [comment]
There was an issue in the service that would cause task installation from extensions to fail (in some cases based on task names). This was impacting the GooglePlay extension and has been resolved. If you see it now, please let us know.

Thanks,
Madhuri

**Comment by eavonius** [comment]
@madhurig we're experiencing this in our release. We've had the VSTS admin enable the extension, but we see a greyed out "Installed" button but none of the associated tasks. How can we proceed with support to fix this?
