### ISSUE TITLE
Extension enabled but tasks missing

### ISSUE THREAD

**Issue by eavonius** [Microsoft/google-play-vsts-extension#113]
We've enabled the extension for our Azure DevOps account, and now we see the extension as "Installed" when attempting to add it to a pipeline in release manager.

But the tasks it's supposed to install are missing as described in #110 .

Not sure the best way to resolve this, but we may try an Azure portal support request.

**Comment by madhurig** [comment]
@eavonius - you can create a support request as well. If you open one, please provide a link to it, so I can follow up. Can you provide your azure devops account name?

Thanks,
Madhuri

**Comment by eavonius** [comment]
Our account name is "tuyatech". I'll try to figure out how to file a request, I guess the Azure DevOps account isn't under our main Azure subscription.

**Comment by eavonius** [comment]
@madhurig I filed a support request through incident reporting available from the Azure DevOps front page. The SR Number is 118112019364576.

**Comment by eavonius** [comment]
@madhurig Yay! We installed it yesterday morning, so I'm not sure why it didn't show up until now. Perhaps whoever looked at the support incident resolved it? Anyway we see the tasks now! Thanks for your (or whoever it was?) help!
