### ISSUE TITLE
Robot is missing a project number

### ISSUE THREAD

**Issue by thecadmann** [Microsoft/google-play-vsts-extension#114]
When trying to publish the APK file using this extension I get the following error:

 ##[error]Error: invalid_grant: Robot is missing a project number.
2018-11-30T22:20:30.9383080Z ##[section]Finishing: Publish to google play

We followed the instructions on how to create the google play console service account but it seems like there is something missing.  I have searched the google console for a project number but did not find one and even if I do find one there is no why to supply to the task

**Comment by thecadmann** [comment]
I was able to fix this by giving the newly created service account release manager permissions for the project.

**Comment by Vannevelj** [comment]
This seems to be a general authentication error. I had it occur because I was using the wrong email address for the service connection (has to be the auto-generated Google Developers service account email).

**Comment by caupolican** [comment]
You saved my bacon. 

> This seems to be a general authentication error. I had it occur because I was using the wrong email address for the service connection (has to be the auto-generated Google Developers service account email).

**Comment by MohamadMousheimish** [comment]
@Vannevelj I was using the wrong email also, but after using the generated email as you mentioned. I got 

> **The caller does not have permission**

Any idea about this problem?

**Comment by agat366** [comment]
> @Vannevelj I was using the wrong email also, but after using the generated email as you mentioned. I got
> 
> > **The caller does not have permission**
> 
> What is the permission that I should give to the user? Should I give permission to the generated email in DevOps project? Or from Google Cloud Platform?

Same here.

**Comment by Vannevelj** [comment]
I don't remember much from when I worked on this so I won't be much help. I did write a article on my blog to document what I did so you could have a look through that and see if anything rings a bell: https://vannevel.net/posts/releasing-android-through-azure-devops
