### ISSUE TITLE
invalid_grant: Robot is missing a project number   google play release task

### ISSUE THREAD

**Issue by TedMobile** [Microsoft/google-play-vsts-extension#123]
Hi

I have release pipeline in azure devops using the  Release tasks.

I keep getting   "[error]Error: invalid_grant: Robot is missing a project number."

I even run with "System.Debug" true but this is all I am getting.

Is there a walkthrough in case I am missing the obvious? I followed this link to set up it

https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play

any suggestions of what that error means?
thanks

**Comment by madhurig** [comment]
This looks like the same issue as https://github.com/Microsoft/google-play-vsts-extension/issues/114. Can you please try the suggestion provided in that issue?

Thanks,
Madhuri

**Comment by madhurig** [comment]
Closing since this looks like a duplicate.
