### ISSUE TITLE
Unable to upload APK with Google Play Extension

### ISSUE THREAD

**Issue by umbgtt10** [Microsoft/google-play-vsts-extension#124]
Good morning 

I have been fighting with this for a long time. Essentially I am getting a strange error when trying to upload my app to goolge play using the extension.

I am fairly sure I have followed all the steps correctly. Yet I am getting the following error message:

loading INPUT_APKFILE
loading INPUT_AUTHTYPE
loading INPUT_CHANGELOGFILE
loading INPUT_LANGUAGECODE
loading INPUT_METADATAROOTPATH
loading INPUT_SERVICEACCOUNTKEY
loading INPUT_SERVICEENDPOINT
loading INPUT_SHOULDATTACHMETADATA
loading INPUT_SHOULDUPLOADAPKS
loading INPUT_TRACK
loading INPUT_VERSIONCODEFILTERTYPE
loaded 22
Agent.ProxyUrl=undefined
Agent.CAInfo=undefined
Agent.ClientCert=undefined
task result: Failed
Unhandled: Unexpected token =
Processed: ##vso[task.issue type=error;]Unhandled: Unexpected token =
Processed: ##vso[task.complete result=Failed;]Unhandled: Unexpected token =

I have an entry open on stackoverflow with all the details:
https://stackoverflow.com/questions/54535389/unable-to-upload-new-apk-to-google-play

Any idea what I am doing wrong?

**Comment by madhurig** [comment]
Hi, 

One thing I noticed in your SO post is that you are providing a full path on disk to the json file. The expectation is for it to be a relative path in the repo. If the path on disk exists, that should work too. Please try removing the " and use / as separator. 

Do you get the same error when you use the endpoint? The private key showing up as empty is a security measure. We don't let you retrieve it via the UI or APIs after the endpoint is saved. 

Thanks,
Madhuri

**Comment by umbgtt10** [comment]
Hi

Thanks a lot for your answer. I get the exact same error if I use an endpoint:

![image](https://user-images.githubusercontent.com/45289332/52459055-4754b080-2b63-11e9-98a4-a0345cce26f3.png)

I have also tried with the Json file as suggested:

![image](https://user-images.githubusercontent.com/45289332/52459764-5c334300-2b67-11e9-8466-2d0d14a0133e.png)

But I am still getting the same result.

Another thing you should know is that I am using TFS express (Version 15.112.26307.0).

Any other idea?

**Comment by umbgtt10** [comment]
I have upgraded tfs express to the latest version: 16.131.28601.4.
No changes.
Any idea what "token" means in this context?

**Comment by madhurig** [comment]
Please send us full debug logs from your build. If you can't attach them here, please email them to me - madhurig at microsoft.com

**Comment by yacaovsnc** [comment]
This error is very odd.  What should have happened next is the agent will parse and load the task's manifest files:
```
Agent.ProxyUrl=undefined
Agent.CAInfo=undefined
Agent.ClientCert=undefined
check path : C:\Agent\{compuername}\_work\_tasks\GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27\2.142.0\task.json
```
It seems in your case, the task didn't even get loaded. 

Looks like maybe your tasks are corrupted on the build agent?  Can you please check if the task is downloaded to your build agent properly?   You can try delete the "GooglePlayRelease" task from your local build agent, it will be downloaded again.  If the problem persists, please zip up the "GooglePlayRelease" task and send it to me at yacao AT microsoft.com.

**Comment by yacaovsnc** [comment]
You may also try uninstall/reinstall the extension.

**Comment by umbgtt10** [comment]
Let me try both options and let you know.

**Comment by umbgtt10** [comment]
Well I have recreated the deployment pipeline entirely with the newest version of TFS Express and now everything works.
No idea what I was doing wrong before. Thanks for having provided support.

**Comment by madhurig** [comment]
Thanks for the update @umbgtt10 . We believe the extension was somehow corrupted on your instance earlier. If you see that again, let us know.
