### ISSUE TITLE
No longer possible to create a Google Play Service Endpoint

### ISSUE THREAD

**Issue by tobber72** [Microsoft/google-play-vsts-extension#125]
On the https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play#overview page, under "Quick Start / Configuring Your Google Play Publisher Credentials / step 4" it says:

"Click on New Service Endpoint and select Google Play"

but in Azure DevOps (https://dev.azure.com/{organization}/{project}/adminservices) it is no longer possible to create a Service Endpoint for Google Play under "New Service Endpoint". 

I know there is the "JSON Auth File" method but I would rather not check in the JSON file from the developer console into the source repo.

**Comment by madhurig** [comment]
The see "Google Play" as an option in the UI. Were there any issues with installing the extension in your org? Can you try uninstall and re-install of the extension? If you continue to have issues, please send us your azure devops organization name.

Thanks,
Madhuri

**Comment by tobber72** [comment]
Yes, we have previously migrated from TFS (on-premise) to Azure DevOps and that was then the problem occurred. 

When we re-installed the extension it is now possible to add the Service Endpoint for Google Play again, thank you for the help!

Thanks,
Torbjorn
