### ISSUE TITLE
Google Play Release Task is not finishing when run on Microsoft's Agent: Hosted VS2017.

### ISSUE THREAD

**Issue by damianun** [Microsoft/google-play-vsts-extension#126]
Google Play Release Task is not finishing when run on Microsoft's Agent: Hosted VS2017.

`2019-03-13T09:25:49.5377609Z ##[debug]Request Parameters:`
`2019-03-13T10:13:48.6094999Z ##[debug]Re-evaluate condition on job cancellation for step: 'Release com.purplebricks.app.apk to Internal Test'.`
`2019-03-13T10:13:48.6828250Z ##[error]The operation was canceled.`
`2019-03-13T10:13:48.6832036Z ##[debug]System.OperationCanceledException: The operation was canceled.`

Since yesterday (12/03/2019) Google Play Release task seems to be hanging on the following line for us:
`let res: Apk = (await edits.apks.uploadAsync(requestParameters))[0];`

Eventually the task gets cancelled by VSTS pipeline. Full pipleing timeout is set to gracious 60 minutes. This particular task was running for over 40 minutes. This is first time we encountered this issue, usually the task was able to finish under 1 minute.

Not sure if this is related anyhow but it seems, there was some Node.js update rolled out to to Microsoft Hosted build agents and now almost every task is reporting multiple lines of the following warning:
`2019-03-13T09:25:47.5999423Z (node:5040) Warning: Use Cipheriv for counter mode of aes-256-ctr`

I am attaching a log file output for Google Play Release Task, run with full diagnostics on
[18.txt](https://github.com/Microsoft/google-play-vsts-extension/files/2961365/18.txt)

**Comment by madhurig** [comment]
@damianun - thanks for reporting this issue. The agent has been rolled back to node 5 since other integrations were impacted by this change as well. Are you still seeing your releases not completing?

**Comment by damianun** [comment]
@madhurig Thank you for responding so promptly. I had to use manual upload not knowing when the issue might be resolved. 
I will test and confirm shortly whether solution is working or not.

**Comment by damianun** [comment]
Yes, I can confirm solution worked! Thank you.

I still can see multiple lines of  
`Warning: Use Cipheriv for counter mode of aes-256-ctr`
 being reported by various tasks, including Google Play Release one, however I presume this will be due to some other parts of Hosted agent software still using newer version of Node.js.
 
Thankfully this doesn't seem to be affecting us anymore.  
I can see, it has also been reported under [azure-pipelines-image-generation project](https://github.com/Microsoft/azure-pipelines-image-generation/issues/775), so I added my comments there as well.

**Comment by madhurig** [comment]
Thanks for confirming. We are working towards updating the agent and tasks to get rid of that warning.
