### ISSUE TITLE
Getting Error:" Failed to create a new edit transaction for the package "co.example.app". Failed with message: Error: The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console."

### ISSUE THREAD

**Issue by yashwanthBhargav** [microsoft/google-play-vsts-extension#127]
I am getting error : "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console" on deploying my app (production). I tried everything listed in https://stackoverflow.com/a/25655897 but it didin't solve my problem.

TIA.

Update: attaching the log 
![error](https://user-images.githubusercontent.com/33343424/55870592-91c7cd00-5ba6-11e9-8cab-73dfc14c3acb.PNG)

**Comment by madhurig** [comment]
I have seen this before when using the wrong credentials or linking against the wrong project (it was frustrating to track down). It appears to be a configuration error on your part.

**Comment by lkillgore** [comment]
Closing on account of inactivity
