### ISSUE TITLE
Using a secure file path doesn't work for GooglePlayRelease@2

### ISSUE THREAD

**Issue by MouthOfMadness** [microsoft/google-play-vsts-extension#131]
Prepends the value d:\a\1\s to my Library's secure file path of env:DOWNLOADSECUREFILE_SECUREFILE  = d:\a\_temp\myFile.json

**Comment by luigisaggese** [comment]
I suggest to use TFS Service Connections, instead secure file. Maybe could solve

**Comment by MouthOfMadness** [comment]
I worked around this problem by adding the json to my repository
