### ISSUE TITLE
[Feature Request] Draft upload solution

### ISSUE THREAD

**Issue by WoodyWoodsta** [microsoft/google-play-vsts-extension#133]
I'm unable to find a solution to a release pattern I am aiming to achieve with this plugin. Currently done manually, we create releases/versions in the Play Store Console, upload the APKs and then hand the draft version to the client to finish the release process as they wish (adding chaneglogs, etc).

Is it possible to simply upload the APKs to a new release but leave the version in draft, without publishing or rolling the release out?

I've seen that the extension is en-route to migrate to v3 of the play store APIs - is this something that will perhaps be possible with v3?

Thanks in advance!

**Comment by lkillgore** [comment]
As 'Draft'?  No.  'Unpublished'?  Yes.

Something that _might_ work for you would be to setup a release for 'internal test' track.

Or, you could create a release, but leave the 'app availability' as 'unpublished' until it gets handed off.  That would leave the release notes as not part of the initial 'release', but those could be created as a separate release which the uploaded APK could be added to.  (IMO, a better method would be to have a metadata folder and kick off a new release after the notes are added there.)  Once that's done, then click 'Publish'.

**Comment by WoodyWoodsta** [comment]
The unpublish/publish idea makes no sense after the first release. The additional release track seems like a fair idea. Unfortunately while the metadata folder idea makes technical sense, the client is not of a technical perspective and so the best option is not always such in their eyes. I guess I was querying whether or not the Store API allowed this, and if not, it doesn't make sense to keep this issue open. Thanks for the suggestions.

**Comment by lkillgore** [comment]
@WoodyWoodsta, it should be _possible_ to use the Google API yourself and push a 'draft' release.  This extension is [hard-coded](https://github.com/microsoft/google-play-vsts-extension/blob/ead6a228254242d987f4d44ebda758df11190a3a/Tasks/google-play-release/googleutil.ts#L169) to 'complete' it (or set it as 'inProgress' for rolling builds).  Wiring in a way to have this value optionally be 'draft' would probably get you what you're looking for.  It's not currently on the roadmap to add it, but IIRC at least one other user has asked for it.

**Comment by WoodyWoodsta** [comment]
@lkillgore If this is in fact possible, and has been requested by others, I'll re-open.

**Comment by baptiste-nv** [comment]
Definitely a must-have for digital agencies that create releases on behalf of their clients.
I would love to have such option.

**Comment by baptiste-nv** [comment]
I would also add that the current checkbox is misleading. If I uncheck the "Roll out release" checkbox, I expect the release to... not being rolled out (in other words: being kept as draft) ;)
Should probably be renamed to "Limit rollout to a users fraction" checkbox.

**Comment by flbaue** [comment]
That this configuration is missing, is quite a bummer. We use an app id that is only for internal testing, so the configuration in Google Play will always be as 'draft'. Because of this, it is not possible to upload the app with this task.

**Comment by TheObliterator** [comment]
I think I'm hitting the same limitation.

Trying to publish our app to an internal track but get the following error:
**##[error]Error: Only releases with status draft may be created on draft app.**

Surely publishing to the internal track needs to flag it as draft?
We're not yet ready to publish to a release track yet, but can't say a way to overcome this error.


> Starting: GooglePlayReleaseBundle
==============================================================================
Task         : Google Play - Release Bundle
Description  : Release an app bundle to the Google Play Store
Version      : 3.185.1
Author       : Microsoft Corporation
Help         : ms-resource:loc.helpMarkDown
==============================================================================
Found main bundle to upload: D:/a/1/b/Release-Dev/com.acme.helloworld-Signed.aab (version code %s)
Authenticated with Google Play and getting new edit 
Uploading bundle file %s...
Updating track information...
##[error]Error: Only releases with status draft may be created on draft app.
Finishing: GooglePlayReleaseBundle

**Comment by TheObliterator** [comment]
I've added a PR (#268) to provide a workaround for this issue, hopefully it will be of help to anyone encountering the same problem. The PR allows you to set the rollout value to -1 which then flags the release as a draft release (ideal for internal releases which haven't yet been reviewed/approved).

**Comment by DaniilShmelev** [comment]
We now have a task that allows to set the release status: [Google Play Status Update](https://github.com/microsoft/google-play-vsts-extension/pull/282).
Feel free to take a look at the [task docs](https://github.com/microsoft/google-play-vsts-extension#google-play---status-update).
