### ISSUE TITLE
Publish to google started failing

### ISSUE THREAD

**Issue by MouthOfMadness** [microsoft/google-play-vsts-extension#135]

**Comment by MouthOfMadness** [comment]
I just started receiving this error, my last good build was about a week ago.  

It's not clear to me if the publish task is failing on the google play api V3, or it's actually a 64 bit compiler issue.

##[error]Error: Error in edits.commitAsync(): {"cause":{"code":403,"errors":[{"domain":"androidpublisher","reason":"releaseValidationErrorKeyNotCompliantWith64BitRequirementError","message":"Release is not compliant with the Play 64-bit requirement."}]},"isOperational":true,"code":403,"errors":[{"domain":"androidpublisher","reason":"releaseValidationErrorKeyNotCompliantWith64BitRequirementError","message":"Release is not compliant with the Play 64-bit requirement."}]}

My android build task looks like this:
- task: XamarinAndroid@1
    displayName: "build android"
    inputs:
      projectFile: '**/droid.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'    
      msbuildArchitectureOption: x64
      createAppPackage: true

My publish task looks like this:
- task: GooglePlayRelease@2
    inputs:
      authType: 'JsonFile'
      serviceAccountKey: $(googleApi.secureFilePath)      
      apkFile: '$(outputDirectory)/*.apk'
      track: 'internal'
      changeLogFile: 'droid/ReleaseNotes.txt'

**Comment by lkillgore** [comment]
_Posting relevant information from our conversation in #129:_

It seems that you're running into [this](https://developer.android.com/distribute/best-practices/develop/64-bit) issue, which shouldn't be related to the update of the task. It looks like the requirement started to be enforced since August 1st.

**Comment by MouthOfMadness** [comment]
Here's the real fix.

After updating my pipeline to use the GoogleRelease@3 task, I had to hand edit the android csproj file to be  arm64-v8a;x86_64.

It all worked after that.
