### ISSUE TITLE
Promoting from internal test to alpha/beta is excluding my test device from availability

### ISSUE THREAD

**Issue by LeversonCarlos** [microsoft/google-play-vsts-extension#137]
On my pipeline i have a first stage using the "release task" to push the apk and metadata to internal tests.
I check on my testing device (a xiaomi mipad) and the app update is there.
Then, on a second stage i have a "promote task" to promote this release to an alpha channel. 
Success everywhere, even on the play store console, all is ok. But my device doesnt see the update. Not only doesnt see the update. The store says the app isnt compatible with the device.
At first i thought that i have done something to the build the excluded my device from the available devices. But it was even show on the play store console devices catalog as a compatible device.
Then i did this... builded the app... and excuted only the first stage... the release task to the internal test track... and then, gone to the play store console and promoted the version from there to alpha. And this way, the device sees the update on app store, says its compatible and i can install and update.
So, i belive theres something with the promote task.
I tryed to compare the promotion done by the task and the one i did manually on the console. I dont see difference. i dont get it.
Dont know if this isnt the right place to ask for help, sorry for that.
Thanks anyway

**Comment by anatolybolshakov** [comment]
Hi @LeversonCarlos, do you still have this issue?

**Comment by LeversonCarlos** [comment]
To be honest, i've been using the pipeline to publish the package to internal (this works fine), and then use the google console to promote to alpha, then beta, etc... 
Promoting thought pipeline, mess something on the package and it stops been available on devices.
Tnks

**Comment by anatolybolshakov** [comment]
Ok, thanks! So I'm closing it now, please feel free to reopen/create other issue if something will appear
