### ISSUE TITLE
Updating my version for V3

### ISSUE THREAD

**Issue by vsaroopchand** [microsoft/google-play-vsts-extension#144]
Hello, we are currently using V2 of this extension; however, we recently noticed a warning stating we must upgrade to V3 by Dec. 1nd, 2019 in our TFS 2018 environment. Where can we get the V3 extension for TFS 2018?

**Comment by vsaroopchand** [comment]
Just want to add more details. We are sti

**Comment by azaricstefan** [comment]
I have same issue.

**Comment by natpos** [comment]
I can't change the version in TFS2017 DevOps
![image](https://user-images.githubusercontent.com/55678153/70112332-1b358d80-16a9-11ea-95d2-2a56d0a0ec11.png)

**Comment by vsaroopchand** [comment]
In our TFS 2018, we only see 2.* in the dropdown. How do we get the 3.* option to show up?

**Comment by azaricstefan** [comment]
Best solution for you would be to update TFS2018 to Azure DevOps Server latest version.
[Link for getting started with the upgrade](https://docs.microsoft.com/en-us/azure/devops/server/upgrade/get-started?view=azure-devops)

**Comment by anatolybolshakov** [comment]
Hi @vsaroopchand, do you still have an issue with updating to V3?

**Comment by anatolybolshakov** [comment]
@vsaroopchand I'm closing it at the moment due to inactivity - please freel free to reopen it and let us know if you still have issues with updating
