### ISSUE TITLE
##[error]Error: Forbidden

### ISSUE THREAD

**Issue by rinaldosilva** [microsoft/google-play-vsts-extension#145]
I am trying to publish to alpha but receive the following message.
d578ef97-ff0e-461b-bf87-a967e13dd3e3 exists true
Found main APK to upload: /Users/runner/runners/2.160.1/work/1/s/app/build/outputs/apk/meuprojeto/release/app-meuapp-release.apk (version code 156)
Authenticated with Google Play and getting new edit 
##[error]Error: Forbidden

**Comment by arctouch-carlosottoboni** [comment]
Have you checked if the Service Connection/JSON File has the required access? The azure [docs](https://docs.microsoft.com/en-us/appcenter/distribution/stores/googleplay) recommend that you generate a Service Connection/JSON with owner privileges, but it will run with Administrator too.

**Comment by rinaldosilva** [comment]
Thanks @arctouch-carlosottoboni You solve the problem!
