### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by Asinab** [microsoft/google-play-vsts-extension#152]
Hello, 
After updating for V3 support, I get "Error: socket hang up" error (Extension Version:3.160.0).Why is the problem caused? 
Thanks.

**Comment by ruhanijeb** [comment]
I am using google play extension in azure devops to upload bundle version 3.
i am also gettting the same error.

**Comment by cumbiman** [comment]
Same error with the code:

  - task: GooglePlayReleaseBundle@3
    inputs:
      serviceConnection: 'Google Play Connection'
      applicationId: 'xxx.xxx.xxxxx'
      bundleFile: '$(build.artifactStagingDirectory)'
      track: 'internal'
      languageCode: 'en-GB'

**Comment by xmashallax** [comment]
Same error here. I am using the JSON auth setting instead of the serviceConnection, extension version is 3.170, the task is GooglePlayReleaseBundle@3 and the desired track is "beta" in my case.

**Comment by anatolybolshakov** [comment]
Hi @Asinab, do you use self-hosted or microsoft-hosted agent? Does it also spontaneously happens for you or this is a permanent issue?

**Comment by anatolybolshakov** [comment]
Hi @Asinab, I'm closing it at the moment due to lack of activity, please feel free to reopen if this issue still appears for you

**Comment by dan-dekel** [comment]
Same problem here with GooglePlayReleaseBundle V3.174.0. I'm using the JSON file for auth and the production track. Auth is working fine. After 4 minutes the task fails with:

Failed to upload the bundle /home/azp/agent/_work/3/android-bundle.aab. Failed with message: FetchError: request to https://www.googleapis.com/upload/androidpublisher/v3/applications/<package-name>/edits/<edit-id>/bundles?packageName=<package-name>&editId=<edit-id>&uploadType=media failed, reason: socket hang up.

Tried with MS hosted agents (ubuntu 18 & 20, mac) and self-hosted agent (ubuntu 18).

No additional logs appear when diagnostics are enabled

**Comment by Deeeeeeeeeevon** [comment]
Hi @anatolybolshakov, I am also experiencing this issue with V3 when trying to release a bundle to the Play Store's beta track (note: uploading the artefact to the store that was created from the pipeline works). We are using a Microsoft-hosted agent

**Comment by keivanh** [comment]
Same error here: 

```
2021-09-30T07:28:20.5526737Z ##[error]Error: Failed to upload the bundle D:/a/r1/a/androidProduction/androidProduction. Failed with message: FetchError: request to https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/xxxxxxxx/edits/13131343456641483032/bundles?uploadType=media failed, reason: socket hang up.
2021-09-30T07:28:20.5692186Z ##[section]Finishing: Release D:\a\r1\a/androidProduction/androidProduction to beta
```

Build pipeline is on self-hosted agent, publishing to Beta track

Other pipeline, microsoft-hosted publishing to alpha track works

**Comment by anatolybolshakov** [comment]
Hi @Deeeeeeeeeevon @keivanh this seems to be some connectivity issues between agent and google endpoint - if you are sure that there is some issue on DevOps side - please feel free to open a new issue with more details for your case.

**Comment by keivanh** [comment]
Error was persistent with both self-hosted and Microsoft-hosted agents.
At the end I found the problem, in the release task "Bundle path", I missed the file name, it should be either exact file path or wildcard to select all files. Adding the file name to the Bundle path fixed the issue.

Still that error message "failed, reason: socket hang up." is completely misleading here. It should simply show there is no file to publish.

**Comment by anatolybolshakov** [comment]
@keivanh got it, thanks - I created https://github.com/microsoft/google-play-vsts-extension/issues/new to check why it does not validate empty value for this input.
