### ISSUE TITLE
Add bundle release process explanation to README

### ISSUE THREAD

**Issue by carstenhag** [microsoft/google-play-vsts-extension#155]
Hello, could you please document how one builds a bundle and deploys it using this extension inside the README? Bundles aren't mentioned in the README yet.

**Comment by carstenhag** [comment]
Further, it is unclear to me how to build and sign bundles. 

My guess is that I first build them with gradle like I do with apks. The step after that is unclear to me, as there's only a "Signing and aligning APK file" step available and none explicitely for bundles.

**Comment by darrentaft** [comment]
Gradle has a bundleX task.  e.g. where you currently use assembleRelease (or assembleMyFlavourRelease if using flavours) to create an APK, you'd use bundleRelease (or bundleMyFlavourRelease) to create and sign the bundle (assuming you have the signing config in the gradle config).  None of this is specific to this plugin though - these are Android fundamentals.  Once the bundle is created, the README then covers how to publish it with this plugin: https://github.com/microsoft/google-play-vsts-extension#google-play---release-bundle

**Comment by carstenhag** [comment]
![Bildschirmfoto 2020-01-10 um 16 23 57](https://user-images.githubusercontent.com/3776997/72164266-a6e7bb80-33c5-11ea-9464-380c30bc4f9e.png)
Just to further explain, we always had these three steps in order to build, sign and then upload the signed APK to the Play Store or AppCenter.

---

Thanks for the explanation. Just to recap, we need to remove the second step and change the gradle tasks in the first step. Also, the signing stuff has to be included there.

**Comment by darrentaft** [comment]
Personally, I have the signing config within my build gradle (with the keys and file injected using secure parameters). If you chose this route, you'd just need to change your gradlew step to use bundleRelease instead of assembleRelease, and remove the signing step altogether.
Alternatively, you could replace the signing step with a command-line step to manually call jarsigner on the bundle.

**Comment by carstenhag** [comment]
Thanks @darrentaft, I ended up doing it likes this:
* Download secure file for the keystore
* Use variable groups for the keystore passwords
* Use a command line step to run jarsigner

**Comment by DaniilShmelev** [comment]
Google Play Release task is now able to upload both APKs and AABs. Please refer to the [task docs](https://github.com/microsoft/google-play-vsts-extension#google-play-release).
