### ISSUE TITLE
Allow release task to update metadata without uploading the AAB(s)

### ISSUE THREAD

**Issue by cvb941** [microsoft/google-play-vsts-extension#156]
Same things as in #26. The option to uncheck upload APKs is present in the APK release task but not in bundle release task.

At this point, wouldn't it be better to move updating metadata to a separate task? As far as I understand, metadata aren't related at all to the apk/aab, they are related to the store listing itself which is just one instance (and same for alpha/beta/production if I'm correct)

**Comment by frarteaga** [comment]
At least changelogs are specific to every AAB/APK deployment. I suggest the same as @cvb941: 

> move updating metadata to a separate task

Also add an input field for changelogs in the Release and Release Bundle tasks.

**Comment by frarteaga** [comment]
Release Bundle task does not have an input to specify Release notes.

**Comment by DaniilShmelev** [comment]
Google Play Release task supports updating only the store listing. Please refer to the docs if you want more info about this feature: https://github.com/microsoft/google-play-vsts-extension#google-play-release
