### ISSUE TITLE
Forbidden error with Google Play Extension

### ISSUE THREAD

**Issue by jayanthpurushothaman** [microsoft/google-play-vsts-extension#158]
Hi team,

Using the latest Google Play extension from the Marketplace, we receive the following error in the Azure DevOps Pipelines. We have followed the documentation provided at https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play

```[section]Starting: Release **/*.apk to internal
==============================================================================
Task         : Google Play - Release
Description  : Release an app to the Google Play Store
Version      : 3.164.1
Author       : Microsoft Corporation
Help         : ms-resource:loc.helpMarkDown
==============================================================================
afc49dff-9af2-4dfc-96fc-1c13efd2a5db exists true
Found main APK to upload: /azp/agent/_work/1/s/android/app/build/outputs/apk/release/app-release.apk (version code 1)
Authenticated with Google Play and getting new edit 
##[error]Error: Forbidden
##[section]Finishing: Release **/*.apk to internal
```

Is there a way to find out why it is throwing this error?

**Comment by oscarjaergren** [comment]
Had the same error. This is because your service account has not been granted access. 

The service account and project must be linked here.  Make sure Linked Project is the right one.

**Comment by jayanthpurushothaman** [comment]
@oscarjaergren Thanks for your response. We have tried giving full permissions in both **Play Console** and **API console** and project is also linked. We used this link as a reference: 

https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play

**Comment by oscarjaergren** [comment]
No idea then. Could be wrong version code? Version code must always be 1 greater than the last one when uploading to play store. Make sure it gets updated. (Looks like you're uploading a APK with versioncode 1)

**Comment by egor-bryzgalov** [comment]
@jayanthpurushothaman could you please run the pipeline in diagnostics mode to provide us with additional information regarding this issue?

**Comment by egor-bryzgalov** [comment]
Closing the issue due to lack of information, please feel free to reopen it.
