### ISSUE TITLE
Release Bundle task does not have an input to specify Release notes.

### ISSUE THREAD

**Issue by frarteaga** [microsoft/google-play-vsts-extension#162]
In the Release Task it is possible:

![imagen](https://user-images.githubusercontent.com/18072082/76777371-7bdf6680-677e-11ea-8c1f-3af74b2edb8d.png)

but in the Release Bundle task there is no such input.

**Comment by davux** [comment]
I think this is fixed. I'm using the Release Bundle task and there is a field for the Release notes.

**Comment by anatolybolshakov** [comment]
Hi @frarteaga, as @davux said - this option was already added for Google bundle task, I'm closing it at the moment since it seems to be resolved - please feel free to reopen if you have some issues with it
