### ISSUE TITLE
getting error caller does not have permission 

### ISSUE THREAD

**Issue by khatridev** [microsoft/google-play-vsts-extension#163]
I have all the configuration done as described for service connection on google console. Downloaded JSON has entries for **client_email** and **primary key** that I use in my pipeline. However, when I perform release bundle task, I get this errror "caller does not have permission". Am I missing any role assignment in the service connection ! currently I have provided owner and editing role.
following is the log:

Authenticated with Google Play and getting new edit 
##[debug]Creating a new edit transaction in Google Play.
##[debug]Creating a new edit
##[debug]Additional Parameters: {"packageName":"*"}
##[debug]task result: Failed
##[error]Error: The caller does not have permission

Note: I am putting this is internal test track.

**Comment by MohamadMousheimish** [comment]
I have the same issue here

**Comment by khatridev** [comment]
After getting stuck for almost 2 days, I happened to go to developer account -> API access on play console. Saw Emails/Users what I created on google cloud are lying here and waiting for approval.  I granted the access to the Email I configured in the cloud. 

That's it, I did not see that error again.

**Comment by anatolybolshakov** [comment]
Thanks! So since there had been issue with permissions and it was already resolved, closing it
