### ISSUE TITLE
Google Play - Promote task bug

### ISSUE THREAD

**Issue by sixpi** [microsoft/google-play-vsts-extension#166]
Hi,

We use the Google Play - Promote task to promote the version in the beta track to the production track, at some small rollout percentage. This has worked well in the past, but recently (~1 month ago) it started having an additional unexpected behavior. The task still correctly promotes the current release in the beta track to production at the right rollout percentage, but it also creates a new release in the beta track at the same rollout percentage. This new extra release in the beta track has no APKs associated with it, but it does mark the APKs that we are trying to release as deactivated. Were there any changes to the promote task that got released recently that would cause this behavior?

-Bing

**Comment by cofitz1** [comment]
@leantk / @erjohnms / @lkillgore is there any status that can be shared on this?

**Comment by anton-erofeev** [comment]
Hello, @sixpi !
Could you please provide the following information:
- The sequence of tasks that you run (Release, Promote, etc) and the Inputs that you use for these tasks (including rollout percentage)
- Logs for each task (please run the pipeline with the debug option set on)
- Does this bug reproduced every deploy, or from time to time?

**Comment by sixpi** [comment]
Hi @anton-erofeev, I sure can :)

* We run release to beta at 100%, followed by a promote beta -> production.
* I don't think I can get logs for the task until our next release, unless there's some way to run the release and promote tasks in "dry-run" mode. We can't just release a new APK for getting logs from the release pipeline.
* So far, the bug reproduces every time the Promote tasks runs.

**Comment by sixpi** [comment]
Got some logs for the release of a different app - I couldn't see any way to run a release pipeline in debug mode though.

Release to beta task:
2020-05-05T18:10:25.2371001Z Found main APK to upload: D:/a/r1/a/Release/drop/app/build/outputs/apk/userOfficialFull/release/app-signed.apk (version code 200502230)
2020-05-05T18:10:25.3690692Z Authenticated with Google Play and getting new edit 
2020-05-05T18:10:34.1968147Z Updating track information...
2020-05-05T18:10:37.1189279Z APK successfully published!
2020-05-05T18:10:37.1190055Z Track: beta

Promote to production task:
2020-05-05T18:13:39.8577154Z 30a76725-6879-49b8-a8a7-9a5c4625411e exists true
2020-05-05T18:13:39.8617513Z Authenticating with Google Play
2020-05-05T18:13:41.2811651Z Getting information for track beta
2020-05-05T18:13:41.6595370Z Promoting to track production
2020-05-05T18:13:42.3834809Z Cleaning up track beta
2020-05-05T18:13:45.2959535Z APK successfully promoted!
2020-05-05T18:13:45.2961183Z Source track: beta
2020-05-05T18:13:45.2961900Z Destination track: production

**Comment by anton-erofeev** [comment]
Thank you @sixpi !
Could you also provide the logs after your next release?

**Comment by anton-erofeev** [comment]
Closed due to lack of activity, please feel free to reopen.

**Comment by sixpi** [comment]
Hi Anton,

I could not find a way to get the release pipeline to print out debug logs. I was looking through the code for the promote task, and noticed this line: https://github.com/microsoft/google-play-vsts-extension/blob/b24fdb4aeddce482778207ab9abc70db3cea5c75/Tasks/google-play-promote/google-play-promote.ts#L60 which seems to update the rollout percentage for the source track. It seems that this would explain the behavior that I'm seeing - could you take a look?

Thanks!

**Comment by sixpi** [comment]
@anton-erofeev I don't think I have permission to re-open this issue, since I didn't close it.

**Comment by anton-erofeev** [comment]
Hi, @sixpi 
Do you use Team Foundation Server or Azure Devops to run your pipelines? Could you also share the version of the Promote task you are using?

**Comment by sixpi** [comment]
We're using Azure Devops to run our pipeline, the promote task version is 3.170.0

**Comment by ChosenSilver** [comment]
I have been watching this thread and I just wanted to chime in to say we have the same issue,  but for Internal to Alpha rather than Alpha to Beta. We are also using Azure Devops to run the pipelines with promote task version 3.170 as well.

Releasing to the Internal track works as expected, but when we promote from the Internal Track to the Alpha Track, The internal becomes deactivated and it reverts to whatever the previous version was.

**Comment by anton-erofeev** [comment]
Hi, @sixpi , @ChosenSilver 
I want to clarify one detail, do you expect that after the promotion, the previous track will remain unchanged? so after moving from alpha to beta, the alpha will not be cleared?

**Comment by ChosenSilver** [comment]
My scenario us Internal->Alpha. Right now I promote my changes to Internal track so I can validate them, and then I promote to the Alpha track when I am ready for the customer to test them. My expectation would be that both the Internal track and the Alpha track have the same version, but in reality when Internal gets promoted to Alpha the Internal track gets reverted to some previous build instead.

**Comment by sixpi** [comment]
@anton-erofeev Yes, that would be my expectation. Our flow is to release the app onto the Beta track at 100%, and then promote it to the Production track later. I wouldn't expect the Beta track to change in any way when we do the promotion.

**Comment by kytwb** [comment]
@sixpi Browsing through, I just found how-to enable debug logs via https://github.com/microsoft/google-play-vsts-extension/issues/36#issuecomment-273520484.

**Comment by anton-erofeev** [comment]
Hi @sixpi @ChosenSilver ,
We added the ability to disable track cleanup in this PR: https://github.com/microsoft/google-play-vsts-extension/pull/190. This feature will be available in the next release, I will let you know when it will be deployed. Thank you for your cooperation!

**Comment by sixpi** [comment]
Thanks @anton-erofeev!

**Comment by sixpi** [comment]
Also thanks @kytwb for the advice about how to enable debug logs!

**Comment by anton-erofeev** [comment]
Hi @sixpi @ChosenSilver ,
A new version of Google play extension was released: https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play

**Comment by sixpi** [comment]
Thank you @anton-erofeev !
