### ISSUE TITLE
##[error]Error: write EPROTO 140479667709760:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794:

### ISSUE THREAD

**Issue by fernandaakl** [microsoft/google-play-vsts-extension#178]
Hi Team,

We are facing this issue in Google Play - Release task.
Please let me know if you need any other information.

Thanks

**Comment by anton-erofeev** [comment]
Hello, @fernandaakl 
Does this bug occur every run, or from time to time? Could you please run the pipeline with debug mode on and provide these logs and the azure-pipelines.yml file?

**Comment by anton-erofeev** [comment]
Hello, @fernandaakl !
This error occurred when using the old version of googleapi. Therefore, the version was updated in this PR : https://github.com/microsoft/google-play-vsts-extension/pull/180. А fixed version of the task will be available in the next release.
