### ISSUE TITLE
Should "User fraction" be available in the extension?

### ISSUE THREAD

**Issue by rub8n** [Microsoft/google-play-vsts-extension#18]
The field "User Fraction" is called multiple times in the readme but seems to be missing in the actual extension. Should it be available on the extension or is the doc outdated?

**Comment by ryuyu** [comment]
User fraction should be available in the UI in VSTS, but it should only be visible when the Rollout track is selected. Is this not the case anymore?

**Comment by rub8n** [comment]
My mistake. I was interacting with the Destination track and not Rollout track on the rollout task. :(

Closing...
