### ISSUE TITLE
Unable to publish Alpha bundle to Google Play Store

### ISSUE THREAD

**Issue by pMesiha** [microsoft/google-play-vsts-extension#185]
Hello,
I am trying to publish a bundle to Alpha channel on Google Play Store, i followed all the pre-requisites steps and published the first version manually (Status=Published).

I am currently getting the following error:
Failed to upload the bundle D:/a/r1/a/_AndriodApp_CI/XXXX/build/app/outputs/bundle/release/app-release.aab. Failed with message: Error: Access Not Configured. Google Play Developer API has not been used in project XXXXX before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/androidpublisher.googleapis.com/overview?project=XXXXX then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry..

I verified that the API is enabled, the service account have "Release Manager" role on the console, and have Owner" role on the project? i tried to decrease the permission of the service account and got a different error, so the service account credentials is working as expected, something else is wrong? any help is appreciated.

YAML Task:
steps:
- task: ms-vsclient.google-play.google-play-release-bundle.GooglePlayReleaseBundle@3
  displayName: 'Release  to Alpha'
  inputs:
    serviceConnection: 'GooglePlayServiceConnection'
    applicationId: com.XXXXXX
    bundleFile: '$(System.DefaultWorkingDirectory)/_AndriodApp_CI/XXXXXX/build/app/outputs/bundle/release/app-release.aab'
    track: alpha
    rolloutToUserFraction: true

**Comment by sdobrodeev** [comment]
@pMesiha This issue is still actual for you? We found sumilar issue from `fastlane` project - https://github.com/fastlane/fastlane/issues/16593 .

**Comment by pMesiha** [comment]
@sdobrodeev 
it starts working on its own a while ago, sorry for not updating the issue in here. seems oto be an issue on Google side.

thanks a lot for the follow up
