### ISSUE TITLE
Allow multilingual release notes

### ISSUE THREAD

**Issue by davux** [microsoft/google-play-vsts-extension#188]
The "release notes" field in Google Play is actually a multilingual field. For example, if your app supports en-US and es-ES, your release notes look like this:

```
<en-US>
These are the release notes in English.
</en-US>
<es-ES>
Estas son las notas de versión en Español.
</es-ES>
```
However, the Release and Release Bundle tasks only use "release notes" and "language code", assuming there will only by 1 language.

I'm seeing two possible approaches for user experience:
- Accept release note files that contain the language markup like what Google accepts
- Let the user configure release notes in multiple languages in the task configuration UI

Thanks!

**Comment by sixpi** [comment]
Our team would also like this feature - currently we still have to manually upload the release notes for every release.

**Comment by titorodi** [comment]
++

**Comment by sixpi** [comment]
Ping - any plans to support multilingual release notes?

**Comment by anatolybolshakov** [comment]
Hi everyone, we are currently working on more prioritized issues at this moment, but planning to pick it up as soon as we have bandwidth for it.

**Comment by liumiaojq** [comment]
+1 for this feature. This is the last step to fully automate our release pipeline to Google play store

**Comment by DevEddy** [comment]
+1

**Comment by DaniilShmelev** [comment]
We support this functionality via the "Metadata Root Directory" input. You'll need to specify your release notes in a format similar to the Fastlane format. Please refer to the ["Google Play Release" task docs for this input](https://github.com/microsoft/google-play-vsts-extension#google-play-release).
