### ISSUE TITLE
Error upload bundle on Google Play Internal Test

### ISSUE THREAD

**Issue by burakocak** [microsoft/google-play-vsts-extension#189]
Hi,
I get the following error when I run it on **Mac Pro** server.

> 2020-06-22T14:43:16.9067170Z ##[debug]Evaluating condition for step: 'Google Internal Test Upload'
> 
> 2020-06-22T14:43:16.9210510Z ##[debug]Evaluating: succeeded()
> 
> 2020-06-22T14:43:16.9434720Z ##[debug]Evaluating succeeded:
> 
> 2020-06-22T14:43:16.9683230Z ##[debug]=> (Boolean) True
> 
> 2020-06-22T14:43:16.9872000Z ##[debug]Expanded: True
> 
> 2020-06-22T14:43:17.0065160Z ##[debug]Result: True
> 
> 2020-06-22T14:43:17.0350520Z ##[section]Starting: Google Internal Test Upload
> 
> 2020-06-22T14:43:17.2774210Z ==============================================================================
> 
> 2020-06-22T14:43:17.2866690Z Task         : Google Play - Release Bundle
> 
> 2020-06-22T14:43:17.2971880Z Description  : Release an app bundle to the Google Play Store
> 
> 2020-06-22T14:43:17.3064920Z Version      : 3.170.0
> 
> 2020-06-22T14:43:17.3179280Z Author       : Microsoft Corporation
> 
> 2020-06-22T14:43:17.3299820Z Help         :
> 
> 2020-06-22T14:43:17.3428210Z ==============================================================================
> 
> 2020-06-22T14:43:17.4233030Z ##[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
> 
> 2020-06-22T14:43:17.4459100Z ##[debug]System.Exception: A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.
> 
>    at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.<RunAsync>d__24.MoveNext()
> 
> --- End of stack trace from previous location where exception was thrown ---
> 
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 
>    at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.<RunStepAsync>d__1.MoveNext()
> 
> 2020-06-22T14:43:17.4656740Z ##[section]Finishing: Google Internal Test Upload

**Comment by anton-erofeev** [comment]
Hi @burakocak ,
One of the common causes of this error is the mismatch between the architecture of the operating system and the agent. For example, such an error can occur if you install x86 version of the agent on an x64 operating system. Could you please check which version of the agent and operating system you are using (x86 / x64) and share this information?

**Comment by anton-erofeev** [comment]
Hi @burakocak ,
Is this issue still relevant to you?

**Comment by hcknl** [comment]
Hello @anton-erofeev 

Just for clarifying, you mean tfs agent by agent and macOS system arch,  am I right?

Thanks

**Comment by anton-erofeev** [comment]
Hi @hcknl 
Yes, you're right, that’s exactly what I mean

**Comment by hcknl** [comment]
@anton-erofeev As far as I understand, we simply have a macOS machine with x86_64 mojave and agents run on it. Actually I did not understand the context of agent arch.

Btw agent version is 2.131.0

**Comment by anton-erofeev** [comment]
@hcknl Could you please make sure you have Git 2.9.0 or higher installed on your machine? This error can appear if not all prerequisites are executed.
A complete list of prerequisites can be found here: [https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops#check-prerequisites](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/v2-osx?view=azure-devops#check-prerequisites)

**Comment by hcknl** [comment]
Hi, we already have 2.21. for the other prerequisites we need some time, thank you.

**Comment by anatolybolshakov** [comment]
Hi @hcknl, this task uses Node10 execution handler, so there should be NodeJS v10.0 and higher installed on hosted machine - could you please verify which version of node is installed on your machine?

**Comment by anatolybolshakov** [comment]
Hi @hcknl is this issue still actual for you?

**Comment by hcknl** [comment]
Hi, We are going to deploy new server fully upgraded then we will retry it, thank you for your help.

**Comment by anatolybolshakov** [comment]
Hi @hcknl do you have any updates with deployment and testing?

**Comment by anatolybolshakov** [comment]
Hi @hcknl ping :smiley: Is it still actual for you?

**Comment by burakocak** [comment]
hi @anatolybolshakov 
The tfs azure devops migration is expected to be completed by our team. Then we will share our experiences with you.

**Comment by anatolybolshakov** [comment]
Hi @burakocak, do you any updates or ETA for this?

**Comment by anatolybolshakov** [comment]
Hi @burakocak, please let us know if it's still actual for you

**Comment by anatolybolshakov** [comment]
Hi @burakocak I'm closing it at the moment due to inactivity - please feel free to reopen it if it's still actual for you
