### ISSUE TITLE
Release notes file location - how to reference?

### ISSUE THREAD

**Issue by rrdesignweb** [microsoft/google-play-vsts-extension#196]
Hi there, I am not sure if this is the best place to post this question but here it goes:

I have setup a CI azure-pipelines.yml script to build my .apk file with expo (react native framework/platform) and turtle-cli etc.

I also have a release going out to Google Play Store using the google-play-vsts-extension

I am trying to figure out how to add the app release notes file i.e where to add this file in my expo file structure / how it gets bundled with the apk and if I add it as a build step and how to reference it?

Azure Pipelines google-play-vsts-extension
<img width="1018" alt="Screen Shot 2020-08-16 at 1 17 40 pm" src="https://user-images.githubusercontent.com/4110276/90325941-57a1e300-dfc5-11ea-8cb7-ca41e77d7094.png">

Expo File Structure:
<img width="222" alt="Screen Shot 2020-08-16 at 1 25 23 pm" src="https://user-images.githubusercontent.com/4110276/90325946-62f50e80-dfc5-11ea-839b-28abdcd32c53.png">

If anyone can point me in the right direction that would be great

**Comment by alexander-smolyakov** [comment]
Hi @rrdesignweb, there are two ways how to attach a changelog file to release:

1. You can select the `Update metadata`  option and specify the `Metadata root directory`. It means you need to create a folder in the repo where you will store changelog files. You can read more about the metadata folder structure in the [readme](https://github.com/microsoft/google-play-vsts-extension/blob/master/README.md#google-play---release) (_8. Metadata Root Directory_). Just, for example, it will be looking something like this: 
![image](https://user-images.githubusercontent.com/14060121/90374416-259f8800-e07c-11ea-9630-29e52a2804ec.png)

2. You can use the `Release notes (file)` option and specify a path to the changelog file. It means you need to create and add to repo a file where you will store information about changes. For example: `changeLogFile: './changelog.txt'`

But in all cases, you need to store a changelog file in the repo itself.

**Comment by rrdesignweb** [comment]
Hi @alexander-prozorov Thank you for the information! I have added the metadata folder with the change log file in my repo and tried to reference it in the release. After I did a successful rebuild from my updated repo changes then run a release I am getting this message `##[error]Error: Not found metadataRootPath: D:\a\r1\a\metadata` 

<img width="686" alt="Screen Shot 2020-08-19 at 8 59 57 am" src="https://user-images.githubusercontent.com/4110276/90573690-66251000-e1fa-11ea-84be-10c05081af5b.png">

<img width="486" alt="Screen Shot 2020-08-19 at 8 55 16 am" src="https://user-images.githubusercontent.com/4110276/90573413-be0f4700-e1f9-11ea-8c84-b18a5e551941.png">
<img width="230" alt="Screen Shot 2020-08-19 at 8 55 55 am" src="https://user-images.githubusercontent.com/4110276/90573459-d4b59e00-e1f9-11ea-8d7a-96d88f93e6cd.png">

Here is my script also - I may have missed something basic, do I need to create a copy task for instance to my script?
`
# Expo Build

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs: 
   versionSpec: '12.x'
   
  displayName: 'Install Node.js'

- script: |
   npm install
   
   npm install -g expo-cli
   npm install -g turtle-cli

   npx expo login -u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD) 
   
   npx expo publish --non-interactive --release-channel deployment
   
   turtle setup:android
   EXPO_ANDROID_KEYSTORE_PASSWORD=$(EXPO_ANDROID_KEYSTORE_PASSWORD) EXPO_ANDROID_KEY_PASSWORD=$(EXPO_ANDROID_KEY_PASSWORD) turtle build:android -u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD) --keystore-path android/app-name.jks --keystore-alias $(keystore-alias) -t apk --release-channel deployment

  displayName: 'npm install and Expo & turtle build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/Users/runner/expo-apps'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app-name.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app-name.zip'
    ArtifactName: 'android'
    publishLocation: 'Container'
    
  displayName: 'Publish Android'
`

**Comment by alexander-smolyakov** [comment]
@rrdesignweb, could you please provide logs from your pipeline as well?

**Comment by alexander-smolyakov** [comment]
@rrdesignweb, thanks for provided logs!

> With the metadata folder structure below the variable "$(versioncodes)" on the changelog where do we set this and what should the format look like? e.g 1.0.3.txt for example?

The `$(versioncodes)` variable evals automatically in pipeline runtime, It equal to the `versionCode` of your apk file. It meaning if the version code of your app is `4` you need to add a `4.txt` in the `changelogs` folder.


Regarding release notes updates. As I can see from the pipeline you download an artifact and extract it. By default, the GooglePlayRelease task searching the folder with metadata in the source directory (`Build.SourcesDirectory`), in your case you need to provide a path where you extract the archive with metadata.

For example, I extract the archive with the metadata folder into a temp folder (`Agent.TempDirectory`) and then I set  the specific path to the related folder (`metadataRootPath`) in the GooglePlayRelease task:
```
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(Agent.TempDirectory)/metadata.7z'
    destinationFolder: '$(Agent.TempDirectory)'
    cleanDestinationFolder: false

- task: GooglePlayRelease@3
  displayName: 'Release **/*.apk to internal'
  inputs:
    authType: 'JsonFile'
    serviceAccountKey: '$(Agent.TempDirectory)/vsts-info-5c5fc0238fab.json'
    apkFile: '$(Agent.TempDirectory)/app-release_v4.apk'
    track: 'internal'
    shouldAttachMetadata: true
    metadataRootPath: '$(Agent.TempDirectory)/metadata'
```

**Comment by rrdesignweb** [comment]
@alexander-prozorov thanks for the reply. I think I have done what you have described but instead of using $(Agent.TempDirectory) I have used the path location where I archived my zip's. Maybe I am not understanding something?
Do I have to use $(Agent.TempDirectory)?
Both my pipeline and release are successful in archiving, finding extracting both zips (metadata and apk). However nothing is showing up in the google play console.
<img width="949" alt="Screen Shot 2020-08-27 at 8 54 44 am" src="https://user-images.githubusercontent.com/4110276/91364845-fe4a7700-e842-11ea-9b28-3b446210c8fa.png">

**Here is my pipeline script:**

# Expo Build

pool:
  vmImage: 'macOS-latest'

steps:
- task: NodeTool@0
  inputs: 
   versionSpec: '12.x'
   
  displayName: 'Install Node.js'

- script: |
   npm install
   
   npm install -g expo-cli
   npm install -g turtle-cli

   npx expo login -u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD) 
   
   npx expo publish --non-interactive --release-channel deployment
   
   turtle setup:android
   EXPO_ANDROID_KEYSTORE_PASSWORD=$(EXPO_ANDROID_KEYSTORE_PASSWORD) EXPO_ANDROID_KEY_PASSWORD=$(EXPO_ANDROID_KEY_PASSWORD) turtle build:android -u $(EXPO_CLI_USER) -p $(EXPO_CLI_PASSWORD) --keystore-path android/happie-dad-jokes-puns.jks --keystore-alias $(keystore-alias) -t apk --release-channel deployment

  displayName: 'npm install and Expo & turtle build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/metadata'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/metadata.zip'
    replaceExistingArchive: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '/Users/runner/expo-apps'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/HappieDadExpoApp.zip'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/metadata.zip'
    ArtifactName: 'metadata'
    publishLocation: 'Container'
  displayName: 'Publish MetaData'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/HappieDadExpoApp.zip'
    ArtifactName: 'android'
    publishLocation: 'Container'
    
  displayName: 'Publish Android'

<img width="278" alt="Screen Shot 2020-08-27 at 8 53 12 am" src="https://user-images.githubusercontent.com/4110276/91365192-e1627380-e843-11ea-83ea-c4ef282d8941.png">


**Release script**

steps:
- task: ExtractFiles@1
  displayName: 'Extract Metadata'
  inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/_rrdesignweb.react-native-happie-dad-jokes/metadata/metadata.zip'
    destinationFolder: '$(System.DefaultWorkingDirectory)/_rrdesignweb.react-native-happie-dad-jokes'
    cleanDestinationFolder: false

- task: ExtractFiles@1
  displayName: 'Extract APK'
  inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/_rrdesignweb.react-native-happie-dad-jokes/android/HappieDadExpoApp.zip'
    destinationFolder: '$(System.DefaultWorkingDirectory)/_rrdesignweb.react-native-happie-dad-jokes/android'
    cleanDestinationFolder: false

- task: ms-vsclient.google-play.google-play-release.GooglePlayRelease@3
  displayName: 'Internal Test Release '
  inputs:
    serviceConnection: 'Google Play Android Developer'
    apkFile: '$(System.DefaultWorkingDirectory)/_rrdesignweb.react-native-happie-dad-jokes/**/*.apk'
    shouldAttachMetadata: true
    metadataRootPath: '$(System.DefaultWorkingDirectory)/_rrdesignweb.react-native-happie-dad-jokes/metadata'


<img width="697" alt="Screen Shot 2020-08-27 at 9 00 45 am" src="https://user-images.githubusercontent.com/4110276/91365167-d4458480-e843-11ea-9613-22709dbeb3e4.png">

**Comment by alexander-smolyakov** [comment]
@rrdesignweb, as I can see from previous logs archive with metadata contains in the `a_rrdesignweb.react-native-happie-dad-jokes` folder, but in the task, you specify the `_rrdesignweb.react-native-happie-dad-jokes` folder. So could you please run the pipeline with the "[Enable system diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)" option enabled and provide an archive with logs? Also, it would be great if you can share the YAML code of download build artifact tasks from your release pipeline.

**Comment by rrdesignweb** [comment]
Hi @alexander-smolyakov here are my logs for the pipeline and release (i am pretty sure they match up) hopefully this helps diagnose the problem. Thank you alot for your help!
[logs_52.zip](https://github.com/microsoft/google-play-vsts-extension/files/5159111/logs_52.zip)
[ReleaseLogs_55.zip](https://github.com/microsoft/google-play-vsts-extension/files/5159112/ReleaseLogs_55.zip)

**Comment by rrdesignweb** [comment]
Hi there you can close this issue now as I have resolved it now. 
Problem was the fastlane metadata structure being strict as I don't think it liked my metadata.zip being in the metadata folder so I changed the extraction to a different folder.
<img width="484" alt="Screen Shot 2020-09-09 at 8 19 27 pm" src="https://user-images.githubusercontent.com/4110276/92586805-18bc3000-f2da-11ea-8435-b28e2dfa05b4.png">
<img width="270" alt="Screen Shot 2020-09-09 at 8 22 19 pm" src="https://user-images.githubusercontent.com/4110276/92586878-3093b400-f2da-11ea-9739-e232fdba02c9.png">

Thanks for your help!

**Comment by anatolybolshakov** [comment]
Thanks @rrdesignweb! I'm closing it since it's resolved
