### ISSUE TITLE
Can we release the 1st version to internal testers instead of uploading to Google Play Store?

### ISSUE THREAD

**Issue by CherukuriSiva** [microsoft/google-play-vsts-extension#207]
In order to automate the release of app updates to the Google Play store, you need to have manually released at least one version through the Google Play Developer Console.

[https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play)

manually released at least one version through the Google Play Developer Console? 
One version should be released on the Google Play Store 

or

One version we can release to internal app testers?

Currently, we are still in the development phase... if we want to implement CI/CD pipeline without pushing our app to Google Play Store... Can we use this extension? We will release one version manually to Internal Testers and the next time onwards we will automate the process.

**Comment by anatolybolshakov** [comment]
Hi @CherukuriSiva, yes, you can release to internal app testers first time manually, and after that automate this using extension.

**Comment by anatolybolshakov** [comment]
@CherukuriSiva I'm closing it at the moment, please feel free to reopen if you have any further questions here.
