### ISSUE TITLE
Release to Internal 

### ISSUE THREAD

**Issue by wpsun-shipperbee** [microsoft/google-play-vsts-extension#209]
Trying to Release to Internal, get the following error message. I definitely incremented my version code. 

I am assuming it's something I missed, but I am lost as to what. Any advice will be much appreciated.

```
Found main bundle to upload: D:/a/r1/a/app-prod-release.aab (version code %s)
 Authenticated with Google Play and getting new edit 
Uploading bundle file %s...
 ##[error]Error: Failed to upload the bundle D:/a/r1/a/app-prod-release.aab. Failed with message: Error: APK specifies a version code that has already been used..
```

**Comment by anatolybolshakov** [comment]
Hi @wpsun-shipperbee was this issue resolved for you?

**Comment by wpsun-shipperbee** [comment]
@anatolybolshakov , it did not. I went with a different approach. So I don't need the answer to this question any more.
