### ISSUE TITLE
Release task doesn't upload additional APK

### ISSUE THREAD

**Issue by zurdev** [Microsoft/google-play-vsts-extension#22]
When specifying additionalApks input variable, the task uploads a single APK.
There's a bug in the code that iterates through the array of APK:
for (var apk in apkFileList) {
    currentEdit = currentEdit.then(function (res) {
        console.log(`Uploading APK file ${apkFileList[apk]}...`);
        return addApk(packageName, apkFileList[apk]);
    });
}
The variable apk in the anonymous function is not updating between iterations. The suggested fix is to iterate over apkFileList with forEach.

**Comment by madhurig** [comment]
Issue has been resolved correctly in latest version (1.2.3) of the extension : https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play
