### ISSUE TITLE
Feature request: Add support for inAppUpdatePriority

### ISSUE THREAD

**Issue by tdekoning** [microsoft/google-play-vsts-extension#220]
Google supplies a way to add an `inAppUpdatePriority` to the upload of each apk or aab file, this essentially means that the app can make use of the [In app updates](https://developer.android.com/guide/playcore/in-app-updates) mechanism of Android, including the fine-grained method of specifying what the importance is of each deploy.

For this to properly work, the priority needs to be specified per version of the deployed app. I would imagine you would need to expand the "review approval" feature to allow the user to specify what priority should be used for this deploy.

The `googleapis` npm package already supports this [feature](https://github.com/googleapis/google-api-nodejs-client/blob/eaa1128d5439096bea9d40b0da0796e9f044215c/src/apis/androidpublisher/v3.ts#L1112)

**Comment by SebastienForay** [comment]
I'm waiting too for this feature to be added ! Would be really appreciated :D

**Comment by SebastienForay** [comment]
PR is my suggestion for adding inAppUpdatePriority support.
Only for APKs as AppBundle task isn't imlemented the same way.

**Comment by tdekoning** [comment]
@SebastienForay nice to see you've created the update to add the ability!

I haven't looked into the internals of the tasks, but would this also be possible to include this in the app-bundle variant? This will be very usefull, seeing Google is going to require everyone to upload aab files soon.

**Comment by SebastienForay** [comment]
@tdekoning That was my first dive in TypeScript, so I may have missed or misunderstood some things, but one thing I'm sure is that my PR WORKS for APKs, I've successfully got the _inAppUpdatePriority_ value with PlayCore 👌

I'll try to improve it for App Bundles (as I'll also have to migrate to this). I'm waiting to see what project maintainers think of it :)

**Comment by tdekoning** [comment]
@SebastienForay Ahh i see, i've scanned the code of the task and they seem awfully similar, so hopefully it will only take a copy paste action from your changes. 

Do you think you have time for this? If not, then i can see if i can make some time free to port your change to the bundles task. 

But i wouldn't want to steal your thunder 😂

**Comment by SebastienForay** [comment]
@tdekoning Did you already moved to AppBundle ?

**Comment by tdekoning** [comment]
@SebastienForay yes, at Q42 we use app bundles for (almost) all our apps, including the ones with many users. 
It helps reduce the size of the package for the user and allows you to use dynamic feature modules (instant apps!).

**Comment by SebastienForay** [comment]
@tdekoning I should have worked on it until end of week :)

**Comment by SebastienForay** [comment]
@tdekoning Hey ! I've updated my PR with the appropriate changes in GooglePlayReleaseBundle task to add inAppUpdatePriority support :)
I've tested in my CI build + release pipelines and I got the update in app 👍 

Now, I have no idea if it will be merged as is or if more work will be needed, and when it'll be merged 😄 

ps: you can build and deploy the PR yourself if you really need it ASAP (https://github.com/microsoft/google-play-vsts-extension/blob/master/CONTRIBUTING.md#build)

**Comment by tdekoning** [comment]
@SebastienForay You are a true hero! 😄

**Comment by SebastienForay** [comment]
> @SebastienForay You are a true hero! 😄

I absolutely NEED this in my CI 🙈

**Comment by DaniilShmelev** [comment]
Thanks @SebastienForay for your contribution! These changes will be rolled out in the nearest future

**Comment by DaniilShmelev** [comment]
The changes have been deployed
