### ISSUE TITLE
Error: <!DOCTYPE html> using Google Play - Release Bundle Task

### ISSUE THREAD

**Issue by JrgSirr** [microsoft/google-play-vsts-extension#222]
Im having an issue at the end of the Google Play - Release Bundle task and this is the error:

`2021-01-21T20:05:27.0726036Z ##[section]Starting: Release Bundle to internal
2021-01-21T20:05:27.0844930Z ==============================================================================
2021-01-21T20:05:27.0845258Z Task         : Google Play - Release Bundle
2021-01-21T20:05:27.0845543Z Description  : Release an app bundle to the Google Play Store
2021-01-21T20:05:27.0845797Z Version      : 3.174.0
2021-01-21T20:05:27.0846201Z Author       : Microsoft Corporation
2021-01-21T20:05:27.0846905Z Help         : ms-resource:loc.helpMarkDown
2021-01-21T20:05:27.0847576Z ==============================================================================
2021-01-21T20:05:28.4812138Z 892d381e-72ca-4cfe-99ec-80901150ce79 exists true
2021-01-21T20:05:28.4836835Z Found main bundle to upload: D:/a/r1/a/build/Artefacto/MisurtiiProduccion 3.4.aab (version code %s)
2021-01-21T20:05:28.5351891Z Authenticated with Google Play and getting new edit 
2021-01-21T20:05:28.8085388Z Uploading bundle file %s...
2021-01-21T20:06:01.8784563Z Appending changelog D:\a\r1\a\build\ReleaseNotes\releaseNotes
2021-01-21T20:06:01.8786882Z Updating track information...
2021-01-21T20:07:02.1938107Z ##[error]Error: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

2021-01-21T20:07:02.1990977Z ##[section]Finishing: Release Bundle to internal`

Im not sure what is this step doing or what option should i check/uncheck and I have to clarify that bundle is getting correctly released to the assigned track, however, related Error: <!DOCTYPE html> makes stage to fail and also the pipeline.

Thanks.

**Comment by anatolybolshakov** [comment]
Hi @JrgSirr does it happen constantly or is this some intermittent error?

**Comment by JrgSirr** [comment]
> 
> 
> Hi @JrgSirr does it happen constantly or is this some intermittent error?

Hi @anatolybolshakov, it happend with the first execution of that release task.

**Comment by ka05** [comment]
I am also experiencing this issue:

Starting: GooglePlayReleaseBundle
==============================================================================
Task         : Google Play - Release Bundle
Description  : Release an app bundle to the Google Play Store
Version      : 3.174.0
Author       : Microsoft Corporation
Help         : ms-resource:loc.helpMarkDown
==============================================================================
d037bddf-40ce-4461-b5fb-702d7e7d7760 exists true
Found main bundle to upload: /Users/runner/work/1/dev-release-aab/app-release.aab (version code %s)
Authenticated with Google Play and getting new edit 
Uploading bundle file %s...
Updating track information...
##[error]Error: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

Finishing: GooglePlayReleaseBundle

I have re-run my pipeline from scratch several times now and still observing the same behavior. I have logged into the Play Console and see that the bundle was uploaded and is pending approval, but this error is holding up my pipeline from being able to continue onto the next stage.

**Comment by NPadrutt** [comment]
Same here. As @ka05  mentioned, the package was uploaded correctly despite the error.

**Comment by evilpilaf** [comment]
We're facing the same issue as @NPadrutt and @ka05 mention.

**Comment by JrgSirr** [comment]
@ka05, have you recently tried to release a bundle using this task?

**Comment by ka05** [comment]
@JrgSirr Earlier today I re-ran my pipeline and this task did succeed! 

Does anyone have any info on why this happened or how likely it is to occur again?

**Comment by JrgSirr** [comment]
@ka05 yeap, that's why i wanted to confirm. I also re-ran my pipeline and passed without that previous error.

**Comment by chowarth** [comment]
Seeing this same error across multiple pipelines using the `Google Play - Release Bundle Task` when pushing a build to the internal test track.

As @NPadrutt already mentioned, we are also seeing that the packages have been uploaded to the PlayStore correctly when viewing the internal test track.

**Comment by max-zaytsev** [comment]
It looks like the issue related to [Google Cloud Incident](https://status.cloud.google.com/incident/cloud-dns/21001) and not to the task itself. It was created almost at the same time this issue was opened.

**Comment by anatolybolshakov** [comment]
@chowarth do you still face with this issue?

**Comment by JrgSirr** [comment]
> 
> 
> @chowarth do you still face with this issue?
@anatolybolshakov 

- Internal test track: same issue

- Alpha track: no errors

**Comment by alexander-smolyakov** [comment]
@JrgSirr, could you please re-run the pipeline with the “[Enable system diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)” option enabled and share the following information:
- YAML file of your pipeline
- Full pipeline logs with system diagnostics information
- What type of agent are you using? (Self-hosted or Microsoft-hosted)

Thanks!

**Comment by chowarth** [comment]
> > @chowarth do you still face with this issue?
> > @anatolybolshakov
> 
> * Internal test track: same issue
> * Alpha track: no errors

We've not been seeing the issue for the last few days.

**Comment by alexander-smolyakov** [comment]
@JrgSirr, is this issue still actual to you?

**Comment by ka05** [comment]
I have also not seen this issue in the past few days.

**Comment by anatolybolshakov** [comment]
Hi everyone, let me close this issue since it seems to be resolved and was related to issue on Google Cloud side - please let us know if it's still actual for you.
