### ISSUE TITLE
Deobfuscation path visible only if Update Metadata is selected

### ISSUE THREAD

**Issue by kkalisz** [microsoft/google-play-vsts-extension#231]
**Task:**
Google Play - Release

**Issue**: 
"Deobfuscation path" field is visible only if "Update metadata" checkbox is set

**Expected behaviour:**
"Deobfuscation path" visible even without "Update metadata" checkbox set

**Investigation:**
It looks that visibility rule is fine
>{
>      "name": "mappingFilePath",
>      "type": "filePath",
>      "label": "ms-resource:loc.input.label.mappingFilePath",
>      "defaultValue": "",
>      "required": false,
>      "helpMarkDown": "ms-resource:loc.input.help.mappingFilePath",
>      "visibleRule": "shouldUploadApks = true && shouldUploadMappingFile = true"
 >   }

But I think that issue may be related to this PR [193](https://github.com/microsoft/google-play-vsts-extension/pull/193)
as it was directly impacting "shouldUploadApks" element. Unfortunately I'm not familiar with extensions so I'm not able to investigate this further.

![image](https://user-images.githubusercontent.com/5392781/106303278-3f174380-625a-11eb-911f-333fa780a825.png)
![image](https://user-images.githubusercontent.com/5392781/106303329-4e968c80-625a-11eb-9f9b-38938fc841db.png)

**Comment by alexander-smolyakov** [comment]
Hey @kkalisz, a [PR](https://github.com/microsoft/google-play-vsts-extension/pull/237) with the fix was merged. The fix will be shipped with the next release of the extension.

**Comment by liumiaojq** [comment]
@alexander-smolyakov Is there an ETA when this fix is shipped? I have another issue #210 where it fails to find the correct mapping file, and this fix could help to work around by explicitly specifying mapping file path

**Comment by alexander-smolyakov** [comment]
@kkalisz, @liumiaojq a [release](https://github.com/microsoft/google-play-vsts-extension/releases/tag/v3.185.0) with the fix has been published. I am closing it at the moment, if the problem still appears, feel free to reopen it.
