### ISSUE TITLE
Force upgrade option with azure dev ops build pipeline

### ISSUE THREAD

**Issue by mohit1993** [microsoft/google-play-vsts-extension#233]
Hi all, 

I am looking for api, or flag in json which can force update my app on google play store , which will be equivalent to inAppUpdatePriority on Google Play Developer API.
I have integrate code to support that in my android app, just wonder how can i set priority of my release while uploading apk.

**Comment by anatolybolshakov** [comment]
Hi @mohit1993 currently there's no support for this parameter in Googe play release task, but since googleapis already [supports](https://github.com/googleapis/google-api-nodejs-client/issues/2186) for this - this would be a good enhancement. We will keep you updated about the progress regarding this feature.

**Comment by mohit1993** [comment]
Ok i get it, we are near close to release our app to play store now, Is there any way that we can do force update with release Task or DevOps? Similar to what play store provides.
We are building Microsoft whiteboard Android app. I think we can use ECS/Control tower but is there any way which provides automatic handling of UI etc.

**Comment by anatolybolshakov** [comment]
@mohit1993 unfortunately there's no way to do it using task at the moment.
You can use google api directly in a pipeline to achieve this.

**Comment by mohit1993** [comment]
What do you mean by "You can use google api directly in a pipeline to achieve this"
As we are planning to use DevOps Service to build and release app on google play store we can only control parameters for DevOps environment. I am not able to find any api in azure devops services to enable force upgrade.
Kindly put some light on to it how we can use google api directly in a pipeline.

**Comment by anatolybolshakov** [comment]
@mohit1993 you can do this manually via script, although I agree this is no a plain way to do this.
We are planning to implement this enhancement soon, but working currently on more prioritized issues - please feel free to contribute if you already have a vision of how to implement this.

**Comment by SebastienForay** [comment]
Hi !

Is issue #220 equivalent to what you need ? I've made a PR (#246 ) to add inAppUpdatePriority support when releasing new APKs :)

**Comment by DaniilShmelev** [comment]
This issue is now supported in the Google Play Release task. Please refer to the [docs](https://github.com/microsoft/google-play-vsts-extension#google-play-release) and look for the "Set in-app update priority" input.
