### ISSUE TITLE
Choosing the suitable application for deployment *.apk package.

### ISSUE THREAD

**Issue by Rrusl** [microsoft/google-play-vsts-extension#241]
Hi,

I have one project in google play and three applications.
How can I choose separated application for deployment new beta version by Azure pipeline using your extension (Google Play - Release).
I see following rows:
- Authentication
- APK path
- Track
and others, but I can't find application name row.
As result I can't manage properly what apk file should be deployed to which application.

Could you explain how it works?

**Comment by EzzhevNikita** [comment]
@Rrusl Google play release task automatically receives application id from the APK file that was passed as a parameter, so no need to pass the app id separately. The task will update an app to which the APK file belongs.

**Comment by Rrusl** [comment]
Oh, fine.

Thank you for quick response.

**Comment by EzzhevNikita** [comment]
@Rrusl Can we close this item, or you have any additional questions?

**Comment by Rrusl** [comment]
HI,

Yes, I have an additional question.
What role should have my service account in google play for auto deployment new versions of my application to google play?

**Comment by EzzhevNikita** [comment]
@Rrusl You can take a look in [Fastlane docs](https://docs.fastlane.tools/actions/upload_to_play_store/#setup) how you need to setup your service account.

**Comment by Rrusl** [comment]
Thank you, I have solved the issue.

You can close this item.
