### ISSUE TITLE
Feature Request: Add support to upload multiple app bundle (AAB)

### ISSUE THREAD

**Issue by bluekyu** [microsoft/google-play-vsts-extension#243]
When using multiple version (ex, API level) in build variant, multiple app bundles are built.
In this case, a release can have multiple app bundle files.

References:
- https://developer.android.com/guide/app-bundle#aab_format
- https://developer.android.com/studio/build/build-variants
- https://discuss.bitrise.io/t/deploy-multiple-aab-android-app-bundles-with-a-single-step/11848

**Comment by DaniilShmelev** [comment]
Hey @bluekyu! Thanks for submitting this feature request.
Multiple apk/aab support has been added to the GooglePlayReleaseV4 task recently.
If you face any issues with the new task, feel free to open a new ticket.
