### ISSUE TITLE
Upload symbols with release task

### ISSUE THREAD

**Issue by BiliBoomBo** [microsoft/google-play-vsts-extension#249]
Hello, I'm using release task to upload my app to google play store, but I don't find anyway to upload native debug symbols together, do I miss it or it haven't supported that?

**Comment by anatolybolshakov** [comment]
Hi @BiliBoomBo this feature is not supported yet, but we are planning to add this soon.

**Comment by BiliBoomBo** [comment]
Got it, thanks.

**Comment by max-zaytsev** [comment]
Hi @BiliBoomBo, 

We investigated the possibility of downloading native debug symbols, but faced the issue of downloading mapping.txt and native-debug-symbols.zip simultaneously.

Could you please tell us if you only want to upload native debug symbols in your case, or you need mapping.txt as well?

**Comment by max-zaytsev** [comment]
Hi @BiliBoomBo, is this issue still actual for you?

**Comment by BiliBoomBo** [comment]
Sorry for late response. In my case, I need to upload both mapping.txt and symbols.zip.

**Comment by BiliBoomBo** [comment]
What's more, I need to upload

**Comment by ankurverma85** [comment]
I need this too
