### ISSUE TITLE
Internal Error Encountered - :shrug: 

### ISSUE THREAD

**Issue by blundell** [microsoft/google-play-vsts-extension#252]
![image](https://user-images.githubusercontent.com/655860/111492892-fac20300-8734-11eb-89a4-b63e86350448.png)

Could you improve your error messaging. How am I supposed to act on this? Please advise :-)

**Comment by anatolybolshakov** [comment]
Hi @blundell there seem to be some error coming from google api - could you please re-run it in debug mode?

**Comment by blundell** [comment]
Sorry this was an intermittent error, it happened for about 30 minutes then resolved itself. It also happened a couple of weeks before that. If it happens again I can run in debug. 

But for sake of this issue, it would be really nice to have better error messaging. Especially if it was to say "Potentially Google API error." Because then I can go chase the right ppl for the fix :-)

**Comment by kuleshovilya** [comment]
Hello @blundell . We've looked into the issue, and it seems that to enable better messaging for that task would require a serious overhaul of error handling, so for now, we would just recommend running debug mode in case of errors.
