### ISSUE TITLE
Feature request: Input paramater to define Release-Name | GooglePlayReleaseBundle

### ISSUE THREAD

**Issue by Bonnyfication** [microsoft/google-play-vsts-extension#257]
### Request
I would like to define a Release-Name for the Task GooglePlayReleaseBundle as an input.

### Current Situation
A release-bundle uploaded with the Task GooglePlayReleaseBundle gets uploaded with the app version as name.
This results in a displayed name of: **1.0.0**

### Expected default
If i upload an release-bundle manually, google sets the name in the format of buildNumber (version) for example: **202103304 (1.0.0)**
This makes it a lot easier to visually set apart the internal releases in the dashboard and compare buildNumbers without expanding the items. For our internal tests normally only the build number changes.

Please change the default name or create a input that allows us to define a Release-Name.

**Comment by tatyana-kostromskaya** [comment]
Hello @Bonnyfication, I have made necessary changes for this feature and they will be available next release.

**Comment by tatyana-kostromskaya** [comment]
New version of the extension was released
