### ISSUE TITLE
Allow release task to update metadata without uploading the APK(s)

### ISSUE THREAD

**Issue by zurdev** [Microsoft/google-play-vsts-extension#26]
Currently, you can upload APK(s) without the metadata. It would help if you could update the metadata without uploading the APK(s).
The suggestion is to add a checkbox to allow skipping APK upload. When selected, it will hide the APK and additional APK(s) inputs, and upload of APK(s) will be skipped.

**Comment by AlexRukhlin** [comment]
Implemented
