### ISSUE TITLE
##[error]Error: Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true.

### ISSUE THREAD

**Issue by Vaahik** [microsoft/google-play-vsts-extension#270]
Error in upload to google play internal track.
##[error]Error: Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true., Once committed, the changes in this edit can be sent for review from the Google Play Console UI.
Last success upload May 06 2021.

- task: GooglePlayReleaseBundle@3
  displayName: Upload release to Google Play
  inputs:
    authType: 'JsonFile'
    serviceAccountKey: '$(Agent.TempDirectory)/*********-development-8b46aa71543a.json'
    applicationId: 'am.***.****'
    bundleFile: '$(build.artifactStagingDirectory)/android/bundle/release/app-release.aab'
    track: 'internal'
    shouldUploadMappingFile: true
    mappingFilePath: '$(build.artifactStagingDirectory)/android/mapping/release/mapping.txt'

**Comment by alexander-smolyakov** [comment]
Hey @Vaahik, Could you please re-run the pipeline with the “[Enable system diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)” option enabled and share the pipeline logs with system diagnostics information?

**Comment by Vaahik** [comment]
[googlesuccess.txt](https://github.com/microsoft/google-play-vsts-extension/files/6459116/googlesuccess.txt)

**Comment by Vaahik** [comment]
Error in last operation. edits.commit
https://developers.google.com/android-publisher/api-ref/rest/v3/edits/commit

**Comment by Vaahik** [comment]
I found a solution.
the error disappears if the In review status is set in the Google Play Console.
I think that the error is in Method: edits.commit.
In the parameter changesNotSentForReview.

**Comment by vladislav-ryzhov** [comment]
Hi @Vaahik 
Do you mean you changed some option in your Google Play Console and it started working?
Before this task started to fail, were there any rejections for your updates in the Google Play Console?

**Comment by Vaahik** [comment]
I change status to In review. And pipeline stage upload is done. But new packages also is status In review.
Before, i upload package (Playstore Console interface) in Alpha - Closed testing, and change status in review.

**Comment by Vaahik** [comment]
> Before this task started to fail, were there any rejections for your updates in the Google Play Console?

Yes. review reject.

**Comment by vladislav-ryzhov** [comment]
Hey @Vaahik we have rolled out related changes.
You can find the required option in the advanced group.

**Comment by vladislav-ryzhov** [comment]
For now, I am closing the issue. Feel free to reopen it if you still have trouble with this task.
