### ISSUE TITLE
Feature: A new task to release apks and bundles (multiple) as part of a same release

### ISSUE THREAD

**Issue by raghuraamms** [microsoft/google-play-vsts-extension#279]
Google has introduced a new feature wrt bundles: Add code transparency. More details can be found here: https://developer.android.com/guide/app-bundle/code-transparency

As part of this Google recommends apps making use of this feature release apks and bundles as part of the same release. I was able to confirm with Google contacts that the REST APIs of Google support the same. So the ask is for the plugin to add a task which supports the same as well.

**Comment by DaniilShmelev** [comment]
Google Play Release now supports this functionality. Please refer to the [docs](https://github.com/microsoft/google-play-vsts-extension#google-play-release).
