### ISSUE TITLE
Agents won't accept a job that uses this plugin.

### ISSUE THREAD

**Issue by rtsketo** [microsoft/google-play-vsts-extension#283]
After many hours of trial and error, I managed to narrow down what was causing our agents not to run a job. When commenting out the below task in the pipeline, the job is accepted and build starts.

```
- task: GooglePlayReleaseBundle@3
  inputs:
    authType: 'JsonFile'
    serviceAccountKey: '$(googlePlay.secureFilePath)'
    applicationId: 'com.axiomc.bocantamivi'
    bundleFile: 'app/build/outputs/bundle/release/app-release.aab'
    track: 'beta'
  condition: eq(variables['Build.SourceBranch'], variables['test'])
  displayName: 'GPlayRelease: Beta'
```

I've also made sure that the secure file is downloaded, there isn't any problem there.
The plugin version used is 3.189.0. Our Azure DevOps version is 2020 (not 2020.1), Dev18.M170.6.
Below I'm gonna paste all of our agents' capabilities.
I also tried different agent versions, I have enlisted them all.

Can you tell me please if I'm missing a demand of this plugin?

| |   |  
-- | -- | --
  | Agent.Version | 2.190.0 / 2.187.2 / 2.186.1 / 2.185.1 / 2.184.2 / 2.183.1 / 2.182.2 / 2.170.1|   |  
  | Agent.ComputerName | RTLAPTOP |   |  
  | Agent.HomeDirectory | d:\Dev\Agents\Agent1 |   |  
  | Agent.OS | Windows_NT |   |  
  | Agent.OSArchitecture | X64 |   |  
  | Agent.OSVersion | 10.0.19043 |   |  
  | ALLUSERSPROFILE | C:\ProgramData |   |  
  | ANDROID_HOME | D:\Dev\SDK |   |  
  | ANDROID_SDK_ROOT | D:\Dev\SDK |   |  
  | AndroidSDK | D:\Dev\SDK |   |  
  | AndroidSDK_25 | D:\Dev\SDK\platforms\android-25 |   |  
  | AndroidSDK_26 | D:\Dev\SDK\platforms\android-26 |   |  
  | AndroidSDK_28 | D:\Dev\SDK\platforms\android-28 |   |  
  | AndroidSDK_29 | D:\Dev\SDK\platforms\android-29 |   |  
  | AndroidSDK_30 | D:\Dev\SDK\platforms\android-30 |   |  
  | AndroidSDK_31 | D:\Dev\SDK\platforms\android-31 |   |  
  | APPDATA | C:\Users\deadl\AppData\Roaming |   |  
  | AZP_AGENT_DOWNGRADE_DISABLED | true |   | 
  | Cmd | C:\Windows\system32\cmd.exe |   |  
  | CommonProgramFiles | C:\Program Files\Common Files |   |  
  | CommonProgramFiles(x86) | C:\Program Files (x86)\Common Files |   |  
  | CommonProgramW6432 | C:\Program Files\Common Files |   |  
  | COMPUTERNAME | RTLAPTOP |   |  
  | ComSpec | C:\Windows\system32\cmd.exe |   |  
  | DotNetFramework | C:\Windows\Microsoft.NET\Framework64\v4.0.30319 |   |  
  | DotNetFramework_2.0 | C:\Windows\Microsoft.NET\Framework\v2.0.50727 |   |  
  | DotNetFramework_2.0_x64 | C:\Windows\Microsoft.NET\Framework64\v2.0.50727 |   |  
  | DotNetFramework_3.0 | C:\Windows\Microsoft.NET\Framework\v3.0 |   |  
  | DotNetFramework_3.0_x64 | C:\Windows\Microsoft.NET\Framework64\v3.0 |   |  
  | DotNetFramework_3.5 | C:\Windows\Microsoft.NET\Framework\v3.5 |   |  
  | DotNetFramework_3.5_x64 | C:\Windows\Microsoft.NET\Framework64\v3.5 |   |  
  | DotNetFramework_4.8.0 | C:\Windows\Microsoft.NET\Framework\v4.0.30319 |   |  
  | DotNetFramework_4.8.0_x64 | C:\Windows\Microsoft.NET\Framework64\v4.0.30319 |   |  
  | DriverData | C:\Windows\System32\Drivers\DriverData |   |  
  | HOMEDRIVE | C: |   |  
  | HOMEPATH | \Users\*****  |   | 
  | InteractiveSession | True |   |  
  | java | C:\Program Files\Java\jre1.8.0_301 |   |  
  | java_8_x64 | C:\Program Files\Java\jre1.8.0_301 |   |  
  | JAVA_HOME | C:\Program Files\Amazon Corretto\jdk11.0.12_7 |   |  
  | jdk | C:\Program Files\Java\jdk-11.0.12 |   |  
  | jdk_11_x64 | C:\Program Files\Java\jdk-11.0.12 |   |  
  | jdk_8_x64 | C:\Program Files\Java\jdk1.8.0_301 |   |  
  | LOCALAPPDATA | C:\Users\deadl\AppData\Local |   |  
  | LOGONSERVER | \\RTLAPTOP |   |  
  | MSBuild | C:\Windows\Microsoft.NET\Framework\v4.0.30319\ |   |  
  | MSBuild_2.0 | C:\Windows\Microsoft.NET\Framework\v2.0.50727\ |   |  
  | MSBuild_2.0_x64 | C:\Windows\Microsoft.NET\Framework64\v2.0.50727\ |   |  
  | MSBuild_3.5 | C:\Windows\Microsoft.NET\Framework\v3.5\ |   |  
  | MSBuild_3.5_x64 | C:\Windows\Microsoft.NET\Framework64\v3.5\ |   |  
  | MSBuild_4.0 | C:\Windows\Microsoft.NET\Framework\v4.0.30319\ |   |  
  | MSBuild_4.0_x64 | C:\Windows\Microsoft.NET\Framework64\v4.0.30319\ |   |  
  | MSBuild_x64 | C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
  | NUMBER_OF_PROCESSORS | 12 |   |  
  | OneDrive | C:\Users\*****\OneDrive |   |  
  | OneDriveConsumer | C:\Users\*****\OneDrive |   |  
  | OS | Windows_NT |   |  
  | Path | C:\Program Files\Java\jdk1.8.0_301\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;D:\Dev\SDK\platform-tools\;C:\Program Files\Gource\cmd;C:\Users\deadl\AppData\Local\Microsoft\WindowsApps; |   |  
  | PATHEXT | .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC |   |  
  | PowerShell | 5.1.19041.1023 |   |  
  | PROCESSOR_ARCHITECTURE | AMD64 |   |  
  | PROCESSOR_IDENTIFIER | Intel64 Family 6 Model 158 Stepping 10, GenuineIntel |   |  
  | PROCESSOR_LEVEL | 6 |   |  
  | PROCESSOR_REVISION | 9e0a |   |  
  | ProgramData | C:\ProgramData |   |  
  | ProgramFiles | C:\Program Files |   |  
  | ProgramFiles(x86) | C:\Program Files (x86) |   |  
  | ProgramW6432 | C:\Program Files |   |  
  | PROMPT | $P$G |   |  
  | PUBLIC | C:\Users\Public |   |  
  | SESSIONNAME | Console |   |  
  | SystemDrive | C: |   |  
  | SystemRoot | C:\Windows |   |  
  | TEMP | C:\Users\*****\AppData\Local\Temp |   |  
  | TMP | C:\Users\*****\AppData\Local\Temp |   |  
  | USERDOMAIN | RTLAPTOP |   |  
  | USERDOMAIN_ROAMINGPROFILE | RTLAPTOP |   |  
  | USERNAME | ***** |   |  
  | USERPROFILE | C:\Users\***** |   |  
  | VERBOSE_ARG | 'SilentlyContinue' |   |  
  | windir | C:\Windows

**Comment by DaniilShmelev** [comment]
Hi @rtsketo! There is an `npm` demand present on all google play tasks currently, so to resolve this issue you need to install npm on your machine and restart the pipeline agent to rescan agent's capabilities.
Closing the ticket for now, feel free to ping me if you have any issues.

**Comment by rtsketo** [comment]
Thank you. I spent so many hours on this. Is there any place where I could have found the answer by myself?

**Comment by DaniilShmelev** [comment]
@rtsketo unfortunately, this is an undocumented behavior currently. We'll see what we can do about it. For now the only way to check this is through [the task code](https://github.com/microsoft/google-play-vsts-extension/blob/master/Tasks/GooglePlayReleaseBundle/task.json#L13).
