### ISSUE TITLE
Uploading APK to Google Play Console which asks for sensitive/high risk permission

### ISSUE THREAD

**Issue by nishi1612** [microsoft/google-play-vsts-extension#291]
We are currently using Google Play VSTS extension to upload our APK to Google Play Store. In our next release, we need to publish an APK to Google Play Console that requests high risk / sensitive permissions from users. 
As per the guidelines present on Play Console Official Document : href=https://support.google.com/googleplay/android-developer/answer/9214102?hl=en-GB#api, we need to fill in a form providing various details of the app and also need to upload the APK  from UI of Google Play Console.
I have following query related to the instructions mentioned in permissions form : 
Can we go ahead and use Google Play VSTS extension to upload APK and fill up permissions form from UI console? Or do we need to upload APK from UI console?

**Comment by anatolybolshakov** [comment]
Hi @nishi1612 the task simply makes an app release via google api, although if there is no limitations on google api side regarding this - it shoulid work.

**Comment by nishi1612** [comment]
Hi @anatolybolshakov ,

Thanks for quick response. 
Does this mean that even though APK is asking for high risk / sensitive permissions, I can still upload APK to google play console via google play VSTS extension?

**Comment by anatolybolshakov** [comment]
@nishi1612 if it is allowed from google api side to fill in high risk / sensitive permissions after apk upload via UI console - yes, it should be possible.

**Comment by anatolybolshakov** [comment]
Hi @nishi1612 let me close this ticket here - since at the moment this is not related to the pipeline task itself.
For google api related questions - I would suggest to reach out to google support for further help.
Please feel free to ask any further questions.

**Comment by nishi1612** [comment]
Hi @anatolybolshakov ,

Thanks for the help. I had doubt about uploading apk via pipeline task and since we can do that, we are good to close the ticket.

Thanks,
Nishi
