### ISSUE TITLE
[Bug] VersionCode not showing properly on task while uploading

### ISSUE THREAD

**Issue by pulimento** [microsoft/google-play-vsts-extension#298]
![image](https://user-images.githubusercontent.com/503313/136812654-f7b3dfba-882f-440f-bfff-73839c8dc82d.png)

What happens:
It shows (version code %s) instead of the actual version code.

What should be happening instedad:
It must show the appropiate version code on task log.

Thanks

@juanlao

**Comment by DaniilShmelev** [comment]
@pulimento GooglePlayReleaseV4 has been released; feel free to create a new ticket if you encounter any other issues
