### ISSUE TITLE
Error: Failed to upload the APK D:/a/r1/a/_DocMitr_App-Android-CI/drop/app/build/outputs/apk/release/app-release-unsigned.apk. Failed with message: Error: Cannot update a published APK..

### ISSUE THREAD

**Issue by Kumar1Rajan** [microsoft/google-play-vsts-extension#303]
Not able to upload apk using Visual Studio Team Services Extension for Google Play. 

Error: Failed to upload the APK D:/a/r1/a/_DocMitr_App-Android-CI/drop/app/build/outputs/apk/release/app-release-unsigned.apk. Failed with message: Error: Cannot update a published APK..   

Also getting warning  : 

##[warning]This task is deprecated. Please switch to GooglePlayRelease@4 that will be released in extension version 4.195.0. You can find a migration guide here: https://github.com/microsoft/google-play-vsts-extension/blob/master/docs/google-play-release-migration.md

Please suggest.

**Comment by max-zaytsev** [comment]
Hi @Kumar1Rajan, this warning isn't related to the failure

Could you please re-run the pipeline with the “[Enable system diagnostics](https://docs.microsoft.com/en-us/azure/devops/pipelines/troubleshooting/review-logs?view=azure-devops#configure-verbose-logs)” option enabled and share the following information:
- YAML file of your pipeline
- Full pipeline logs with system diagnostics information
- What type of agent are you using? (Self-hosted or Microsoft-hosted)

**Comment by max-zaytsev** [comment]
Closing this one at the moment due to inactivity - please let us know if you have any further questions.
