### ISSUE TITLE
GooglePlayReleaseBundle@3 - Error after update task to version 3.194.0

### ISSUE THREAD

**Issue by CalabroBax** [microsoft/google-play-vsts-extension#307]
Task : Google Play - Release Bundle 
Version : 3.194.0

Hi, 
After the update the task doesn't work anymore.  The error is : 

> [error]FetchError: request to https://www.googleapis.com/oauth2/v4/token failed, reason: self signed certificate in certificate chain

Running the pipeline with debug logs  : 
![image](https://user-images.githubusercontent.com/92939802/138433563-ab4e1c56-02e4-49bd-acc9-897e9f43aeaa.png)

**Comment by CalabroBax** [comment]
@max-zaytsev 
 Current agent version: '2.182.1' (same for the successful and failed runs)
 and it's not a YAML pipeline, is a classic pipeline in on prem AzureDevOps installation

**Comment by max-zaytsev** [comment]
@CalabroBax could you create a test YAML pipeline (based on your classic) using this [guide ](https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-classic-pipelines?view=azure-devops)-  and try this:
>
> ```YAML
> steps:
> - task: GooglePlayReleaseBundle@3.192.0
>   inputs: ...
> ```
> where 3.192.0 - the version of the task from the last successful run.

**Comment by max-zaytsev** [comment]
@CalabroBax do you have any updates?

**Comment by max-zaytsev** [comment]
Closing for now. Please reopen if you still have any questions
