### ISSUE TITLE
Documentation: wrong parameter for bundle upload

### ISSUE THREAD

**Issue by benventive** [microsoft/google-play-vsts-extension#308]
Hi there,

I used the [migration documentation](https://github.com/microsoft/google-play-vsts-extension/blob/master/docs/google-play-release-migration.md#releasing-a-single-bundle-file) to update our pipelines and I noticed a tiny mistake in the bundle release sample: the documentation indicates to use the 'apkFile' parameter when the proper one would be 'bundleFile'.

This is just a minor change but I think it could help people with the migration!

**Comment by alexander-smolyakov** [comment]
A related PR (#309) was merged. So let me close the issue as well.
