### ISSUE TITLE
Wildcards don't work for "Additional APK Path(s)"

### ISSUE THREAD

**Issue by Performensch** [Microsoft/google-play-vsts-extension#31]
After we split our APK into two to target specific CPU architectures and reduce the package size I ran into following problem:

When using the additional APK path(s) option it seems that wildcards and/or relative paths don't seem to work. Instead the VSTS extension tries to load the APK in relation to it's own location on the build agent.

The config for the "main" APK: _**/app-android-armv7-release.apk_
The config for the additional APK path(s): _**/app-android-x86-release.apk_

The main APK is found and used correctly, the additional is not as you can see in the attached log.

[task_log.txt](https://github.com/Microsoft/google-play-vsts-extension/files/484393/task_log.txt)

I also tried all kinds of relative paths within the source to get the extension to find the file, with and without wildcards, still no luck.
My current workaround is to use absolute local paths on the build agent to upload the file which I won't admit to if I was asked if I really did that. :)

**Comment by Performensch** [comment]
Since I got access to our build agent I took a look at the extension (and added some extra log calls) and noticed the following:

`var apkFile = resolveGlobPath(tl.getPathInput("apkFile", true));`

results in _resolveGlobPath_ receiving _D:\TfsBuildAgent\work\13\s\**\app-android-armv7-release.apk_ which can be resolved/found but the call

`apkFileList.push(resolveGlobPath(additionalApks[i]));`

sends just _**/app-android-x86-release.apk_ to _resolveGlobPath_

I'm neither a JavaScript nor a VSTS extension coder but it seems to me that _getPathInput_ does more than just retrieve the raw value from the input field and this has to be replicated for the array of additional APKs too.

**Comment by ryuyu** [comment]
You are correct, there appears to be a bug here around globs that aren't rooted.
If you are still having this issue, could you try specifying $(Agent.BuildDirectory)/**/app-android-x86-release.apk in the multiple apk box and see if that resolves it?

The correct thing would be for us to assume that unrooted glob are relative to the working directory of the project.

**Comment by AlexRukhlin** [comment]
Implemented with the commit [aac3b95](https://github.com/Microsoft/google-play-vsts-extension/commit/aac3b95fc7975af926b3263664b7db4588aae59f)
