### ISSUE TITLE
Getting Error While Updating from Version 3.194.0 to 4.195.1

### ISSUE THREAD

**Issue by yashpalraj** [microsoft/google-play-vsts-extension#311]
![image](https://user-images.githubusercontent.com/17542387/139424539-e5ad7640-7da3-4069-99e6-0f490cda9f00.png)

**Comment by djonik1562** [comment]
When expect a new version?

**Comment by anatolybolshakov** [comment]
Hey @djonik1562 we are planning to release new version today - will let you know once it's released.

**Comment by tatyana-kostromskaya** [comment]
Hi @djonik1562 , @yashpalraj we have just released new version of the extension.

**Comment by djonik1562** [comment]
> Hi @djonik1562 , @yashpalraj we have just released new version of the extension. Please let us know if you are able to install it.

All ok. Thank you!

**Comment by yashpalraj** [comment]
@tatyana-kostromskaya Sure. I will check and update you on the same.
Thank You.

**Comment by yashpalraj** [comment]
@tatyana-kostromskaya  Hi, the issue has been resolved. Thanks for your prompt update.
