### ISSUE TITLE
GooglePlayReleaseV4 sends changes to review even if option changesNotSentForReview is set to false

### ISSUE THREAD

**Issue by devops-ninja2021** [microsoft/google-play-vsts-extension#324]
GooglePlayReleaseV4 works fine for me now. But i dont understand something. Although I dont select the option 

![image](https://user-images.githubusercontent.com/10422347/149266492-abc9b1cc-938b-4e7a-b878-05e29cc7b008.png)

my Apks are sent directly for review. is there a way to prevent this? I wish also there was option to select multiple release note files for different languages

_Originally posted by @EmilAlipiev in https://github.com/microsoft/google-play-vsts-extension/issues/301#issuecomment-1011789251_

**Comment by EmilAlipiev** [comment]
yes this option seems to be still not working. and actuall release notes as well although I followed the correct structure I believe. I will create a separate issue for this. thanks for creating this issue

**Comment by KBEMobisys** [comment]
Fastlane had the same issue and they solved it this way:
https://github.com/fastlane/fastlane/pull/19248/files

Maybe this helps to solve it in a same or similar way here.

**Comment by KBEMobisys** [comment]
Could the owner have a look into the pull request? It solves the problem for us.

**Comment by EmilAlipiev** [comment]
When trying to publish an internal testing, it even happens worse that I get error message although
 I dont have this option below checked but still getting the error as "Changes cannot be sent for review automatically. Please set the query parameter changesNotSentForReview to true." Maybe UI and setting is confused and should be other way around?

![image](https://user-images.githubusercontent.com/10422347/208325635-376a1c56-d786-45c7-a111-ef637feb4bef.png)

**Comment by devops-ninja2021** [comment]
Hello EmilAlipiev, the bugfix of PR #327 is still not merged into the master branch. If it was merged you will find an additional switch "Retry commit if changesNotSentForReview failed" which fixes the error.

**Comment by devops-ninja2021** [comment]
PR #327 was merged and fixed the issue. So I will close this one.
