### ISSUE TITLE
Multiple release notes not working

### ISSUE THREAD

**Issue by EmilAlipiev** [microsoft/google-play-vsts-extension#325]
As advised I have followed the fastlane documentation but seems to be not working for me. here is how it looks like
my folders and file structure

<img width="272" alt="image" src="https://user-images.githubusercontent.com/10422347/156406140-81c7f75f-6223-4762-985c-f61060aab327.png">

Pipeline

![image](https://user-images.githubusercontent.com/10422347/156406554-4e609102-79db-4949-9ca1-3729e329d141.png)

is there something missing or wrong here?

**Comment by alexander-smolyakov** [comment]
Hi @EmilAlipiev, according our [docs](https://github.com/microsoft/google-play-vsts-extension/blob/master/README.md) the metadata folder structure should be the following:
```
$(Specified Directory)
   └ $(languageCodes)
     ├ full_description.txt
     ├ short_description.txt
     ├ title.txt
     ├ video.txt
     ├ images
     |  ├ featureGraphic.png    || featureGraphic.jpg   || featureGraphic.jpeg
     |  ├ icon.png              || icon.jpg             || icon.jpeg
     |  ├ promoGraphic.png      || promoGraphic.jpg     || promoGraphic.jpeg
     |  ├ tvBanner.png          || tvBanner.jpg         || tvBanner.jpeg
     |  ├ phoneScreenshots
     |  |  └ *.png || *.jpg || *.jpeg
     |  ├ sevenInchScreenshots
     |  |  └ *.png || *.jpg || *.jpeg
     |  ├ tenInchScreenshots
     |  |  └ *.png || *.jpg || *.jpeg
     |  ├ tvScreenshots
     |  |  └ *.png || *.jpg || *.jpeg
     |  └ wearScreenshots
     |     └ *.png || *.jpg || *.jpeg
     └ changelogs
       └ $(versioncodes).txt
```

Which means that the name of changelog file should align with app version. 

For example:
If the `versionCode` of application is set to `4919`, then the name of changelog file should be `4919.txt` and the path to this file will be `metadata/en-US/changelogs/4919.txt`

**Comment by EmilAlipiev** [comment]
I see but according to do fast lane default is used if there is no file with version number which makes good sense if you just wanna make a quick update with default text like "bug fixing" etc. So it reduces the work. I would even rather always update default.txt and track with source control instead of creating a new file everytime

**Comment by alexander-smolyakov** [comment]
@EmilAlipiev I have opened a feature request to implement a support for `default.txt` files
- #326

Let me close this ticket, since currently the `GooglePlayReleaseV4` pipeline task works as expected.
