### ISSUE TITLE
[GooglePlayReleaseV4] Add support of the `default.txt` for changelog files

### ISSUE THREAD

**Issue by alexander-smolyakov** [microsoft/google-play-vsts-extension#326]
**Task**:
- GooglePlayReleaseV4

**Description**:
In current implementaion the name of change log file must alig with version code of application.

```
$(Specified Directory)
   └ $(languageCodes)
     ├ full_description.txt
     ├ short_description.txt
     ├ title.txt
     ├ video.txt
     ├ images
     └ changelogs
       └ $(versioncodes).txt
```

Since the format of `metadata` folder is quite similar to fastlane’s [supply tool](https://github.com/fastlane/fastlane/tree/master/supply#readme) we can add support of the `default.txt` to simplify the work with changelog files.

For example:

```
Metadata
   └ en-US
     ├ full_description.txt
     ├ ...     
     ├ images
     └ changelogs
       ├ `default.txt`   
       └ 1100.txt
   └ fr-FR
     └ changelogs
       ├ `default.txt`   
       └ 1100.txt
```
**Related issue**:
- #325

**Comment by denis-tikhomirov** [comment]
PR - https://github.com/microsoft/google-play-vsts-extension/pull/331

**Comment by anatolybolshakov** [comment]
Rolled out these changes with new extension release.
