### ISSUE TITLE
Feature Request: Don't fail the pipeline if changelog too long

### ISSUE THREAD

**Issue by Buzzker** [microsoft/google-play-vsts-extension#328]
I love the Task for the Pipelines.
Though, I have a problem with a changelog. Pipeline fails if the number of symbols in the file exceeds 500.
I have a changelog.md file with all Versions, how do I cut it?
Like:
```
# 3.0.55
- lorum ipsum

# 3.0.54
- lorum ipsum
- lorum ipsum
- lorum ipsum
- lorum ipsum

# 3.0.53
- lorum ipsum
```

I would be fine if the pipeline just gets first 500 symbols from the file.

**Comment by max-zaytsev** [comment]
Hi @Buzzker,
This extension uses _fastlane_ tool to upload changelogs. So you need to organize your files in the following format:
https://docs.fastlane.tools/actions/supply/#changelogs-whats-new

You can check this comment for more details: https://github.com/microsoft/google-play-vsts-extension/issues/109#issuecomment-437639412

Please try this and let us know if you still have any issues.

**Comment by max-zaytsev** [comment]
@Buzzker, do you have any updates?

**Comment by max-zaytsev** [comment]
@Buzzker, closing this. Please reopen if you still have any questions.
