### ISSUE TITLE
"set in-app update priority" is invisible

### ISSUE THREAD

**Issue by yzhang108** [microsoft/google-play-vsts-extension#340]
When I using the "Google Play Release", I choosed the action as "Upload single bundle", 
![image](https://user-images.githubusercontent.com/11496559/165891407-32b88d14-c55a-4d62-8d6a-7a913244b19f.png)
but "set in-app update priority"  is invisible under "Advanced Option"
![image](https://user-images.githubusercontent.com/11496559/165891518-5dfcd8e1-7f2e-4f1b-8133-08628c6a0695.png)
How to make it visible?

**Comment by max-zaytsev** [comment]
Hi @yzhang108, did you manage to solve your problem?
As I can see "set in-app update priority" was moved from "Advanced Options". This input is now a little higher.

**Comment by max-zaytsev** [comment]
@yzhang108 I'm closing this. Please reopen the issue if you still have any questions.
