### ISSUE TITLE
Possible fraudulent clones of extension

### ISSUE THREAD

**Issue by bartsipes** [microsoft/google-play-vsts-extension#353]
Just based on the name, logo, and description these two extensions in the marketplace seem like clones of this extension. Even the report an issue links at the bottom on both lead here. 

https://marketplace.visualstudio.com/items?itemName=YingjieLi-Demo.google-play-with-halt
https://marketplace.visualstudio.com/items?itemName=dshmelev.ds2-google-play

**Comment by LiliaSabitova** [comment]
Hi @bartsipes thanks for reporting! We will figure it out.

**Comment by LiliaSabitova** [comment]
Hi @bartsipes mentioned extensions have been deleted.
