### ISSUE TITLE
azure devops with play store upload apk instantly error

### ISSUE THREAD

**Issue by anilakuzum** [microsoft/google-play-vsts-extension#361]
Hello , azuredevops with release step using play store when I want to upload I get the error in the picture. All my information is absolutely correct.

![image](https://user-images.githubusercontent.com/3521437/195947859-dcfe2c26-4549-4202-b5a8-e58046da7435.png)

![image](https://user-images.githubusercontent.com/3521437/195948044-c9cfa9d6-2f01-4e8d-a804-fff1930ace2c.png)

**Comment by LiliaSabitova** [comment]
Hi @anilakuzum thanks for reporting! We are working on more prioritized issues at the moment but will get back to this one soon.

**Comment by anilakuzum** [comment]
Hi @LiliaSabitova , I solved the problem.
