### ISSUE TITLE
Date is sent as release app version on Google Play

### ISSUE THREAD

**Issue by bharatmsft** [microsoft/google-play-vsts-extension#382]
Hi,

I am observing an issue in which "Date" is being send as app release version name (attaching images for your reference).

1. This is how it looks like on Google Play console. You can see that for the 1st track, there is version present and for the second there is date instead of actual app version
![date-instead-of-version-cropped](https://user-images.githubusercontent.com/104906536/213868410-9074ca51-ccff-467e-897d-b9be74cca965.png)

2. A comparison of agent logs for the same tasks (in which we started seeing this issue) 2 weeks apart. You can see "date" being sent in one image and correct app version sent in another.
![current-release](https://user-images.githubusercontent.com/104906536/213868415-5fbfea11-3a7a-4dbe-956e-986e0ccc0c5d.png)
![prev-release-obfuscated](https://user-images.githubusercontent.com/104906536/213868421-28b44a58-5ce6-4868-85f8-f119fcb4ceed.png)

Please note that we've not done any changes to our release pipelines in a while, and we were not observing any issues with our last published build around 2 weeks ago. Also, surprisingly this issue isn't happening for all tracks on current build and we're observing it on about half of our Google Play Testing tracks (these affected tracks are super critical for our testing though and have good number of audience).

**Comment by DmitriiBobreshev** [comment]
Hi @bharatmsft, thank you for reporting, as I see in a googleapi doc, the name of TrackRelease, If not set, the name is generated from the APK's version_name. If the release contains multiple APKs, the name is generated from the date. ([link](https://googleapis.dev/nodejs/googleapis/latest/androidpublisher/interfaces/Schema$TrackRelease.html)), so, by any chance is it possible that you uploaded multiple APKs?

In case not, could you please provide part of the pipeline where you create a new release, and, if it's possible, part ob task logs with debug flag? If you can't share it here, you can send the logs via email directly to me(v-bobreshevd@microsoft.com)

**Comment by DmitriiBobreshev** [comment]
Seems like a bug with ADO, created an issue, and responded in teams. Close the issue on GitHub because not related to the task itself.
