### ISSUE TITLE
No application was found for the given package name

### ISSUE THREAD

**Issue by noahwebster** [Microsoft/google-play-vsts-extension#39]
When I try and deploy my project, I get this error from the Release step:

Authenticated with Google Play and getting new edit
{ [Error: No application was found for the given package name.]
cause: { [Error: No application was found for the given package name.] code: 404, errors: [ [Object] ] },
isOperational: true,
code: 404,
errors: 
[ { domain: 'global',
reason: 'applicationNotFound',
message: 'No application was found for the given package name.',
locationType: 'parameter',
location: 'packageName' } ] }

I've setup the app in the Play store. How do I set the package name so it sees the link? It seems to be able to connect, but doesn't upload the files.

**Comment by xzhe** [comment]
Hi, can you send me the log file for further investigation? It is better to set the variable "system.debug" to true so we can see the debug messages. You can either paste the log here or send me an email. My email address is xzhe@microsoft.com. Thanks!

**Comment by noahwebster** [comment]
Thanks. E-Mail sent.

**Comment by madhurig** [comment]
@noahwebster : Was the issue resolved with Zhen. Zhen is no longer on the team, so if you continue to have issues, please respond and I will help.

**Comment by noahwebster** [comment]
Yes, we solved the issue, thanks!


________________________________

**Comment by madhurig** [comment]
@noahwebster : Thanks!

**Comment by CaLxCyMru** [comment]
Hi @noahwebster - What was the solution that was provided to you by @xzhe?

**Comment by noahwebster** [comment]
You have to manually upload a project to Google first, either through their site, or through Visual Studio. Once that is done, the extension will work.
