### ISSUE TITLE
Cannot install extension

### ISSUE THREAD

**Issue by mgj** [Microsoft/google-play-vsts-extension#42]
I click the "install" button on the marketplace and get the following error:

Extension operation denied by event callback. The task.json file was not found for contribution _build/Tasks/GooglePlayRelease

**Comment by ygeelen-tb** [comment]
We are experiencing the same issue

**Comment by DavidStaheli** [comment]
Thanks for reporting this.  I've verified the problem too.  I contacted our Marketplace team to help resolve it.

**Comment by jeffyoung** [comment]
There is a fix being deployed at this time but I do not have an ETA on when it will reach all customers.  This issue appears to be affecting other extensions as well (including the Apple App Store extension).

**Comment by jeffyoung** [comment]
Hi @mgj and @ygeelen-tb.  It's my understand that this issue is fixed.  Please re-open if you're still seeing issues.

**Comment by ygeelen-tb** [comment]
Yes it's fixed for me.
