### ISSUE TITLE
Azure Devops Google play release Issue, (##[error]Error: error:1E08010C:DECODER routines::unsupported)

### ISSUE THREAD

**Issue by bharat-shivlab** [microsoft/google-play-vsts-extension#437]
1> Issue in Bundle path:

Also Check my release pipeline script like below::

steps:
task: ms-vsclient.google-play.google-play-release.GooglePlayRelease@4 displayName: 'Release to internal test' inputs: serviceConnection: 'Google Play service connection (create-for-pipeline-account-bk@appwriter-2651e.iam.gserviceaccount.com)' applicationId: com.wizkids.appwriter bundleFile: '**/*.aab' changeLogFile: '-> Test release notes' releaseName: 'AppWriter internal release 001' isDraftRelease: true

we try also some ::

**->APK PATH:** **/*.apk (Not Working)
**->APK PATH:**$(Build.ArtifactStagingDirectory)_AppWriter Android Manual APK & AAB\drop\apk\AppWriter-universal-13-03-2024.apk (Not Working)
**->APK PATH:**$(System.ArtifactsDirectory)/_AppWriter Android Manual APK & AAB/drop/apk/AppWriter-universal-13-03-2024.apk (Not Working) (error:1E08010C:DECODER routines::unsupported)
**->AAB PATH:****/*.aab (Not Working)

**Check screen::**
![ss1](https://github.com/microsoft/google-play-vsts-extension/assets/163845191/4d0b626a-a8cf-43cf-a732-975f5bbd63f8)
![ss2](https://github.com/microsoft/google-play-vsts-extension/assets/163845191/9eb6c631-f136-477d-b406-444b24086f08)
![ss3](https://github.com/microsoft/google-play-vsts-extension/assets/163845191/44cc8b80-b0a1-4b24-ac23-e97bdb092d60)
![ss4](https://github.com/microsoft/google-play-vsts-extension/assets/163845191/ddb0fcc9-906f-4cc2-a4ca-996953206c07)

above is my APK and AAB file Already created but not find a path in the Release Pipeline, how we can fix the issue please send me some details. and also send me (an updated Script)

**Comment by chenrilima** [comment]
i have the same error: ##[error]Error: error:1E08010C:DECODER routines::unsupported, I was trying to solve, but no yet.

**Comment by andrea-rochira** [comment]
I have the same error. How can I solve it?

**Comment by chenrilima** [comment]
> I have the same error. How can I solve it?

i do not remember how I solve it, but a think this error is about key, I used p.12 format and not .jks
