### ISSUE TITLE
Beta release fails when Alpha is present

### ISSUE THREAD

**Issue by OUeland** [microsoft/google-play-vsts-extension#44]
Hi,
We have an on-premise TFS 2015 running version 1.112.0 of the Google Play extension.

When running the "Google Play Release" task to the Beta channel the deployment fails when there is an Alpha release. This seems to happen even if the Alpha release already has been overridden/deactivated by a manual Beta deployment.

We run our build successfully, and the APK is created successfully. We have even tried to promote the Alpha to Beta before deploying the new Beta. Same issue. After a manual Beta deployment the Alpha is listed as superseded by the Beta, and deactivated. In other words a Beta deployment should be possible, but even now it seems to stop on the old Alpha.

I have seen this issue described on forums, but no fix has been presented. Other tools seems to do a specific deactivation of the Alpha before deploying the Beta, in accordance with how Google Developer Console does this. But this is not the case for us. Is this "feature" not present in this extension?

Here is the output from TFS when it fails:

```
2017-03-03T10:48:46.9491733Z Uploading APK file D:/Builds/31/bin/Release/no.locus.transfleetmobile.apk...
 
2017-03-03T10:48:46.9501734Z ##[debug]Uploading a new apk: D:/Builds/31/bin/Release/no.locus.transfleetmobile.apk
 
2017-03-03T10:48:46.9511735Z ##[debug]Additional Parameters: {"packageName":"no.locus.transfleetmobile","media":{"body":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":[],"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":1,"path":"D:/Builds/31/bin/Release/no.locus.transfleetmobile.apk","fd":null,"flags":"r","mode":438,"autoClose":true},"mimeType":"application/vnd.android.package-archive"}}
 
2017-03-03T10:48:58.2793062Z ##[debug]Uploaded version code 5923
2017-03-03T10:48:58.2793062Z Updating track information...
2017-03-03T10:48:58.2803063Z ##[debug]Updating track
2017-03-03T10:48:58.2823065Z ##[debug]Additional Parameters: {"packageName":"no.locus.transfleetmobile","track":"beta","resource":{"track":"beta","versionCodes":[5923]}}
2017-03-03T10:48:58.7033486Z ##[debug]Upload change logs if specified...
2017-03-03T10:48:58.7073490Z ##[debug]Commit all the edits
2017-03-03T10:49:00.6955478Z { [Error: Version 5862 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.]
2017-03-03T10:49:00.6965479Z   cause: { [Error: Version 5862 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.] code: 403, errors: [ [Object] ] },
2017-03-03T10:49:00.6975480Z   isOperational: true,
2017-03-03T10:49:00.6975480Z   code: 403,
2017-03-03T10:49:00.6985481Z   errors: 
2017-03-03T10:49:00.6995482Z    [ { domain: 'androidpublisher',
2017-03-03T10:49:00.7005483Z        reason: 'multiApkShadowedActiveApk',
2017-03-03T10:49:00.7015484Z        message: 'Version 5862 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.' } ] }
2017-03-03T10:49:00.7015484Z ##[debug]task result: Failed
2017-03-03T10:49:00.7025485Z ##[error]Failed to publish APKs. 
```
Note the version numbers above. The 5862 version is the OLD Alpha that has been superseded already, but it is still stopping the deployment.
 
Is there a fix for this?

Thanks!

**Comment by madhurig** [comment]
@OUeland:  It is not clear from your description if you are able to upload version 5923 manually to Beta track from the Google Developer console. Uploading an APK with higher version code to Beta than Alpha should show you an error manually as well.

In the extension we have a "Promote" task that allows you to control this behavior. You can try using the "Promote" task to promote your Alpha to Beta and then upload version 5923 or upload version 5923 to Alpha track and then promote Alpha to Beta track.

Let us know if this helps. If you continue to see errors, please attach a zip of your logs, so I can check the task inputs.

Thanks,
Madhuri

**Comment by OUeland** [comment]
@madhurig: Thanks for answering!

I'm sorry if my description was a little vague. The manual Beta deployment of version 5923 gives no errors, and automatically deactivates the previous Alpha.

I have tested the Promote, but since I had manually deployed to Beta the Alpha is no longer available for Promoting and that gives an error as well, stopping the deployment of the Beta.

In any case the deployment to Beta always gives an error even if the Alpha has been deactivated already, and that can't be correct? If this is intended it seems impossible to deploy directly to Beta as long as an older deactivated Alpha exists?

We do the deployments to Beta manually for now.

Thanks,
Øyvind

**Comment by madhurig** [comment]
@OUeland: What you are trying to do, i.e. publish a new version to Beta when Alpha has been deactivated should work. 

I was able to repro the error you see by doing the following:
1. Upload version 5 to Beta - succeeds
2. Upload version 6 to Alpha - succeeds
3. Upload version 7 to Beta - fails with multiApkShadowedActiveApk. This error is expected behavior.
I then deactivated version 6 in Alpha and published the change, I now see version 6 as "Unpublished" in the Google Developer Console:
![deactivate](https://cloud.githubusercontent.com/assets/3269636/24011557/7ff3b7fe-0a51-11e7-8313-4875fd395f1c.png)
After that I was able to upload version 7 to Beta successfully. 

Can you check in the Google developer console (advanced mode) what the status of version **5862** shows up as for your app?

Thanks,
Madhuri

**Comment by OUeland** [comment]
@madhurig: Perhaps I am expecting too much from the API. I was expecting to have both a Beta and Alpha running simultaneously with different testers on each. The Beta would be close to production ready (or even a bugfix version of the PROD), while the Alpha may contain new features not ready for "large scale" testing.
This is not possible if the Alpha must be deactivated before a new Beta is deployed...

Another thing is deactivating the Alpha is not possible to do from the TFS-task (as far as I know), and then the point of automating is somewhat lost, is it not? If you have to log into the console to deactivate you might as well just upload the new one as well?

Anyway, what I am seeing is that doing the update using the the "old" APK-management page in Google Developer Console will produce the results you are seeing, and it is consistent with what is happening from TFS.

However, Google has launched a new way of managing deployment, and the "old" APK management will be discontinued soon. When I manually deploy a new Beta using the new management page, Google deploys my new Beta and states that the Alpha has been superseded by a newer Beta, however the Alpha is still active (it is in norwegian...):
![image](https://cloud.githubusercontent.com/assets/26163641/24036012/1f720ef6-0af8-11e7-9e37-672402816a77.png)

Thee Alpha version is not deactivated but for users with access to both Alpha and Beta they would get the latest version:
![image](https://cloud.githubusercontent.com/assets/26163641/24036113/77438308-0af8-11e7-9b6b-fc2e0b238f6e.png)

When running the deployment from TFS it will fail, but the new management system in Developer Console seems to handle it without deactivating the Alpha.

I just ran TFS and it failed as expected:
`1.	2017-03-17T08:37:05.3358234Z Set workingFolder to default: C:\Program Files (x86)\Team Foundation Build Agent\tasks\GooglePlayRelease\1.112.0
2.	2017-03-17T08:37:07.2188234Z ##[debug]agent.workFolder=D:\Builds
3.	2017-03-17T08:37:07.2288234Z ##[debug]loading inputs and endpoints
4.	2017-03-17T08:37:07.2318234Z ##[debug]loading ENDPOINT_AUTH_$/
5.	2017-03-17T08:37:07.2378234Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
6.	2017-03-17T08:37:07.2388234Z ##[debug]loading INPUT_APKFILE
7.	2017-03-17T08:37:07.2388234Z ##[debug]loading INPUT_AUTHTYPE
8.	2017-03-17T08:37:07.2398234Z ##[debug]loading INPUT_CHANGELOGFILE
9.	2017-03-17T08:37:07.2408234Z ##[debug]loading INPUT_METADATAROOTPATH
10.	2017-03-17T08:37:07.2418234Z ##[debug]loading INPUT_SERVICEACCOUNTKEY
11.	2017-03-17T08:37:07.2418234Z ##[debug]loading INPUT_SHOULDATTACHMETADATA
12.	2017-03-17T08:37:07.2428234Z ##[debug]loading INPUT_TRACK
13.	2017-03-17T08:37:07.2438234Z ##[debug]loaded 9
14.	2017-03-17T08:37:16.5638234Z ##[debug]check path : C:\Program Files (x86)\Team Foundation Build Agent\tasks\GooglePlayRelease\1.112.0\task.json
15.	2017-03-17T08:37:16.5648234Z ##[debug]set resource file to: C:\Program Files (x86)\Team Foundation Build Agent\tasks\GooglePlayRelease\1.112.0\task.json
16.	2017-03-17T08:37:16.5648234Z ##[debug]system.culture=en-US
17.	2017-03-17T08:37:16.5818234Z ##[debug]authType=JsonFile
18.	2017-03-17T08:37:16.5828234Z ##[debug]serviceAccountKey=D:\Builds\31\s\Config\AndroidKeyStoreFiles\TransFleetMobile-dbdbaea3af14.json
19.	2017-03-17T08:37:16.6008234Z ##[debug]apkFile=D:\Builds\31\bin\Release\no.locus.transfleetmobile.apk
20.	2017-03-17T08:37:16.6098234Z ##[debug]additionalApks=null
21.	2017-03-17T08:37:16.6098234Z ##[debug]track=beta
22.	2017-03-17T08:37:16.6108234Z ##[debug]userFraction=null
23.	2017-03-17T08:37:16.6108234Z ##[debug]changelogFile=D:\Builds\31\s
24.	2017-03-17T08:37:16.6118234Z ##[debug]shouldAttachMetadata=false
25.	2017-03-17T08:37:16.6128234Z ##[debug]Candidate package: D:/Builds/31/bin/Release/no.locus.transfleetmobile.apk
26.	2017-03-17T08:37:16.8588234Z ##[debug]name extraction from apk succeeded: no.locus.transfleetmobile
27.	2017-03-17T08:37:16.8998234Z ##[debug]Updating Global Parameters
28.	2017-03-17T08:37:16.9008234Z ##[debug]SETTING packageName TO "no.locus.transfleetmobile"
29.	2017-03-17T08:37:16.9018234Z ##[debug]One line before end
30.	2017-03-17T08:37:16.9028234Z ##[debug]End Updating Global Parameters
31.	2017-03-17T08:37:17.5058234Z Authenticated with Google Play and getting new edit 
32.	2017-03-17T08:37:17.5058234Z ##[debug]Creating a new edit
33.	2017-03-17T08:37:17.5178234Z ##[debug]Additional Parameters: {"packageName":"no.locus.transfleetmobile"}
34.	2017-03-17T08:37:18.1088234Z ##[debug]Updating Global Parameters
35.	2017-03-17T08:37:18.1118234Z ##[debug]SETTING editId TO "11274872144187669720"
36.	2017-03-17T08:37:18.1128234Z ##[debug]One line before end
37.	2017-03-17T08:37:18.1138234Z ##[debug]End Updating Global Parameters
38.	2017-03-17T08:37:18.1138234Z Uploading APK file D:/Builds/31/bin/Release/no.locus.transfleetmobile.apk...
39.	2017-03-17T08:37:18.1148234Z ##[debug]Uploading a new apk: D:/Builds/31/bin/Release/no.locus.transfleetmobile.apk
40.	2017-03-17T08:37:18.1218234Z ##[debug]Additional Parameters: {"packageName":"no.locus.transfleetmobile","media":{"body":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":[],"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":1,"path":"D:/Builds/31/bin/Release/no.locus.transfleetmobile.apk","fd":null,"flags":"r","mode":438,"autoClose":true},"mimeType":"application/vnd.android.package-archive"}}
41.	2017-03-17T08:37:30.9598234Z ##[debug]Uploaded version code 5975
42.	2017-03-17T08:37:30.9608234Z Updating track information...
43.	2017-03-17T08:37:30.9618234Z ##[debug]Updating track
44.	2017-03-17T08:37:30.9628234Z ##[debug]Additional Parameters: {"packageName":"no.locus.transfleetmobile","track":"beta","resource":{"track":"beta","versionCodes":[5975]}}
45.	2017-03-17T08:37:31.3718234Z ##[debug]Upload change logs if specified...
46.	2017-03-17T08:37:31.3718234Z ##[debug]Commit all the edits
47.	2017-03-17T08:37:33.2928234Z ##[debug]task result: Failed
48.	2017-03-17T08:37:33.2938234Z ##[error]Failed to publish APKs.
49.	2017-03-17T08:37:33.2958234Z { [Error: Version 5935 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.]
50.	2017-03-17T08:37:33.2968234Z   cause: { [Error: Version 5935 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.] code: 403, errors: [ [Object] ] },
51.	2017-03-17T08:37:33.2978234Z   isOperational: true,
52.	2017-03-17T08:37:33.2978234Z   code: 403,
53.	2017-03-17T08:37:33.2988234Z   errors: 
54.	2017-03-17T08:37:33.2998234Z    [ { domain: 'androidpublisher',
55.	2017-03-17T08:37:33.2998234Z        reason: 'multiApkShadowedActiveApk',
56.	2017-03-17T08:37:33.3008234Z        message: 'Version 5935 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes.' } ] }
`
and then took the APK and deployed it manually:

![image](https://cloud.githubusercontent.com/assets/26163641/24036256/0d0d5b34-0af9-11e7-9a6b-89a49ac12211.png)

As you can see the manual deployment went fine. The previous Beta version has been deactivated and a new Beta has been deployed, but the Alpha is still active, but superseded for users with access to both tracks. 

As I mentioned in an earlier post, it seems that other deployment routines for other build systems have implemented a deactivation of older version/tracks as needed. That is what I expected, but it is not possible to do from TFS yet. Perhaps it is coming?

Thanks!

Regards,
Øyvind Ueland

**Comment by madhurig** [comment]
@OUeland: Yes, we only support promote and upload currently. Your workflow to delete/deactivate another version is not available. We will add it to the backlog. Thanks for all the details.

**Comment by alexander-smolyakov** [comment]
Hi, @OUeland! Is this problem still actual to you?

**Comment by OUeland** [comment]
No, I am no longer working in this company so I do not know. The issue can be closed.

**Comment by alexander-smolyakov** [comment]
Closing it since the problem not actual. Feel free to reopen.
