### ISSUE TITLE
Error signing debug variant bundle to publish android app by Azure pipeline

### ISSUE THREAD

**Issue by meltanan** [microsoft/google-play-vsts-extension#442]
Hey 

I have my Azure pipeline building (release variant/environment), signing, and releasing app to production with no issues. 

When I try to build the app for debug/beta variant/environment I get an error when it tries to sign the bundle. I'm using the same YML file, the only thing I changed in YML file ( from release to debug) is "tasks: ':app:bundleRelease'" ---> "tasks: ':app:bundleDebug'". and I was getting this error:  

jarsigner: unable to sign jar: java.util.zip.ZipException: invalid entry compressed size (expected 7521 but got 7106 bytes).

I made sure there is no existing aab file and I did remove //signingConfig signingConfigs.debug

I'm not sure what I'm missing, or if I'm using the script correctly or building the bundle correctly using the task. 

I attached screen shot of my YML file and the error page.

I appreciate any help please. 
![Screenshot 2024-05-28 at 10 21 17 AM](https://github.com/microsoft/google-play-vsts-extension/assets/17438049/694ddb6c-ec14-4ba8-a237-2b77a6ed241b)
![Screenshot 2024-05-28 at 10 27 55 AM](https://github.com/microsoft/google-play-vsts-extension/assets/17438049/a731309e-3914-463b-a3d1-1476d60576b1)

**Comment by meltanan** [comment]
FYI, if I modify the signing script to: instead of SHA225withRSA TO SHA1withRSA and from SHA-225 To SHA1 signing is successful but I get an error when it tries to deploy that there is an issue with signature. And yes this is also for debug variant only!!! If I do it for release there is no issue. 
![Screenshot 2024-05-29 at 5 57 51 PM](https://github.com/microsoft/google-play-vsts-extension/assets/17438049/26e43d05-6d07-4b86-95d8-96f77fdf610c)

**Comment by KonstantinTyukalov** [comment]
Hi @meltanan thanks for the reporting! We are working on higher priority issues, but we'll get back to this one soon

**Comment by KonstantinTyukalov** [comment]
Hi @meltanan, what task do you use from this repository? Could you share the full repro yaml and all repro steps?
thanks

**Comment by meltanan** [comment]
Hi @KonstantinTyukalov 

Download secure file task

Generate bundle for debug task

Sign the generated bundle task

Copy files task

Publish build task

I shared the full yml file by two screen shots

![Screenshot 2024-05-30 at 6 35 27 PM](https://github.com/microsoft/google-play-vsts-extension/assets/17438049/6c6abcc4-2da2-4e5b-87b3-53cbf3d62b24)


![Screenshot 2024-05-30 at 6 35 49 PM](https://github.com/microsoft/google-play-vsts-extension/assets/17438049/5e7bc142-7064-4034-90e7-bc7fc6ce674b)
