### ISSUE TITLE
Trying to ServerEndPoint

### ISSUE THREAD

**Issue by meltanan** [microsoft/google-play-vsts-extension#451]
Hey 

I'm trying to find the ServerEndPoint so I used my service connection name but I'm getting an error. Any idea? 

Error: The pipeline is not valid. Job Job: Step AppCenterDistribute input serverEndpoint expects a service connection of type vsmobilecenter but the provided service connection VantacaV3ManageAndroid is of type google-play.

![Screenshot 2024-07-03 at 1 24 12 PM](https://github.com/microsoft/google-play-vsts-extension/assets/17438049/e68b38d8-2d9a-461b-b880-76b1ae1d519d)

**Comment by ivanduplenskikh** [comment]
@meltanan, on the left of your screenshot is the [GooglePlayRelease](https://learn.microsoft.com/en-us/azure/devops/pipelines/ecosystems/android?view=azure-devops#install-google-play) task which uses [Google Play service connection](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play#:~:text=Click%20on%20New%20service%20connection%20and%20select%20Google%20Play), on the right side is the [AppCenterDistribute](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/app-center-distribute-v3?view=azure-pipelines) task which uses [Visual Studio App Center](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/app-center-distribute-v3?view=azure-pipelines#inputs:~:text=Selects%20the%20service%20connection%20for%20Visual%20Studio%20App%20Center) service connection.

**Comment by ivanduplenskikh** [comment]
@meltanan, I'm closing this issue. Feel free to re-open it if you have any questions about it.
