### ISSUE TITLE
error "Only releases with status draft may be created on draft app."

### ISSUE THREAD

**Issue by Crare** [microsoft/google-play-vsts-extension#467]
we are getting this error "Only releases with status draft may be created on draft app."
Our app is not in released state yet so we don't wanna push it there. But we would want to automate pushing releases to internal testing.
Now I need to do it manually as it only creates draft if I set the param isDraftRelease to true.

relate to comment by lillypaul here: https://github.com/microsoft/google-play-vsts-extension/issues/322#issuecomment-1130518544

what's the solution? do i need to add the draft to other stage or something in google play console? so next time I wouldn't get this error.

Also we are never gonna release this app from this app. it's a dev environment build version. so it is kinda always gonna be "draft app". we are not gonna publish it at least.

**Comment by KonstantinTyukalov** [comment]
Hi @Crare could you please clarify why `isDraftRelease` parameter is not a solution in your case?
thanks

**Comment by Crare** [comment]
Fixed by creating a release draft in next step and doing the required info for Google Play. then it at some point started working. The state of the app changes from draft after that.
