### ISSUE TITLE
Only one screenshot is uploaded per type when updating metadata

### ISSUE THREAD

**Issue by AdamEssenmacher** [Microsoft/google-play-vsts-extension#51]
When set to update metadata, only one screenshot is getting uploaded per type, so one each of phone, 7-inch, and 10-inch. There are no errors or warning in the step log.

**Comment by AlexRukhlin** [comment]
Fixed in https://github.com/Microsoft/google-play-vsts-extension/commit/1ba5eaebd102005caeea47ebc6b80e9c7f3042dd
