### ISSUE TITLE
Upload obb files

### ISSUE THREAD

**Issue by tanwwg** [microsoft/google-play-vsts-extension#56]
Is it possible to upload OBB files via this plugin? I placed the obb file in the same folder as the APK in the right format, but it did not seem to upload.

**Comment by madhurig** [comment]
The extension does not support .obb files. We will consider this enhancement for a future update.

Thanks,
Madhuri

**Comment by GKersten** [comment]
Any updates or timeframe for supporting OBB files? The current version of the task is not usable anymore for my app since I passed the 100MB file size I need to split my APK.

**Comment by DavidStaheli** [comment]
Hi @GKersten, thanks for raising this issue again because it's been around for nearly a year.  I can't say exactly when we'll complete it, but I've added it to our near-term plans and hope to have a more specific date in the next 2 weeks.

**Comment by GKersten** [comment]
@DavidStaheli Thanks for the quick answer. For the time being I will have a look at it, see if I can get something working.

**Comment by GKersten** [comment]
@DavidStaheli Are you able to give some more information about the support of obb files?

**Comment by DavidStaheli** [comment]
@GKersten I'm hoping we can complete it in the next 4-6 weeks.  I'm anxious to get it done.

**Comment by pascal-hauser** [comment]
Any updates on this? Is uploading expansion files (obb) now supported?

**Comment by hammady** [comment]
I have the same issue. My app is using expansion files and I can't use this extension. 
At least I need a way to link to an existing expansion file as it rarely changes. 
Is there a limitation from the Google API side?

**Comment by trondat** [comment]
Any progress on adding expansion files to this extension. It's really annoying that I cannot deploy my project with this extension.

**Comment by anatolybolshakov** [comment]
Added ability to attach obb files in [release 3.170.0 ](https://github.com/microsoft/google-play-vsts-extension/releases/tag/v3.170.0). You can find 'Upload Obb' option in 'Advanced Options' settings group - at the moment you need to locate obb file in the parent directory of apk file. Closing it as already fixed.
