### ISSUE TITLE
Rename repo to "vsts-google-play-extension"

### ISSUE THREAD

**Issue by nschonni** [Microsoft/google-play-vsts-extension#58]
That would seem to fit the naming convention of he rest of the extensions in the GitHub org.

Alternately "vsts-google-play-tasks"

**Comment by jeffyoung** [comment]
Hi @nschonni.  Can you explain what you mean by the "GitHub org"?  This repo is our Team Services extension (and is in the Microsoft org).  We've got a similarly named Apple Store extension at https://github.com/Microsoft/app-store-vsts-extension that is also for Team Services.  I don't think we have plans to rename them.

**Comment by nschonni** [comment]
It was just something I noticed when I was poking around the Microsoft organization on Github for extensions. The majority follow a `vsts-*` naming https://github.com/Microsoft?utf8=%E2%9C%93&q=vsts&type=&language=, but you're right that it isn't :100:
