### ISSUE TITLE
Extension does not work with wildcards

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/google-play-vsts-extension#60]
on the Visual Studio Extension page it shows the apk file being defined as:

> **/*.apk

If you try this in your upload it will show this in the logs:

> After prefix Artifact Path Root provide by JobExtension. The Path is a rooted path, but it is not fully qualified, return the path: C:\agent\_work\r1\a\**\*.apk
> [2017-06-07 11:47:07Z ERR  ReleaseJobExtension] System.ArgumentException: Illegal characters in path.
> Parameter name: path
>    at System.IO.Path.GetFullPath(String path)
>    at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.GetRootedPath(IExecutionContext context, String path)

and fail the upload.

This error is also not passed back to the task in VSO, you need to check the physical log file to find this error:

reported back to the VSO task is:

> ##[error]{"cause":{},"isOperational":true}

Which is not helpful

**Comment by JKennedy24** [comment]
submitted logging issue as seperate issue:
https://github.com/Microsoft/google-play-vsts-extension/issues/62

**Comment by JKennedy24** [comment]
Image showing wildcards used in instructions: [https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play)

![image](https://user-images.githubusercontent.com/9284438/26877175-f53bffc4-4b80-11e7-993f-e6daef96580f.png)

**Comment by madhurig** [comment]
@JKennedy24: What version of the vsts-agent are you using? I am able to use wildcards just the way you have it, and I am working on a fix for the logging issue.

**Comment by JKennedy24** [comment]
Thanks for looking at this. I am using 2.116.1. I notice there is a new version 2.117.1 out. I will update the agent and try wildcards again and update you after our next release cycle

**Comment by madhurig** [comment]
@JKennedy24 : Wildcards should work on the 2.116.1 as well. There might be another error happening that is getting masked by the logging issue.

**Comment by JKennedy24** [comment]
The error is in supplying wildcards for the JSON file by the looks. my release returns the error:

> ##[error]Error: Not found serviceAccountKey: C:\agent\_work\r1\a\**\GooglePlayAuth.json

**Comment by JKennedy24** [comment]
also got:

> 2017-06-29T15:52:43.6802208Z ##[error]Error: ENOENT: no such file or directory, stat 'C:\agent\_work\r1\a\**\ReleaseNotes.txt'

Changing them to hard coded paths worked

**Comment by madhurig** [comment]
@JKennedy24: Wild cards are not supported in the path to the JSON file. Please browse and pick the json file from the UI to set the full path. Most tasks in general provide wild card support for binaries since builds generally put them in different paths and it is cumbersome to enter the path.

Thanks,
Madhuri

**Comment by JKennedy24** [comment]
@madhurig thanks for the confirmation. I will close this bug off as "not supported" its no trouble for me to just pick the path.
