### ISSUE TITLE
Changing Authentication from JSON to Service Endpoint doesnt remove JSON path

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/google-play-vsts-extension#61]
Set authentication type to JSON.
Type an invalid path **/*.json
Now change to service endpoint and enter a endpoint email and key

Now run the task, you will find the task fails because the invalid json path is still being used

**Comment by madhurig** [comment]
@JKennedy24: Thank you for reporting this issue but we are unable to repro it. If you are using "Release", please verify if you modified the current release and ran a new "deploy" or updated the release definition and created a new "release". More information on creating releases and deploying: https://www.visualstudio.com/en-us/docs/build/actions/create-deploy-releases 

Regards,
Madhuri

**Comment by JKennedy24** [comment]
Hi mardhurig, I did create a new release. What I found is if you follow the following steps:
1. set authentication to JSON
2. type path "IAMINVALID"
3. change path to endpoinge and enter endpoint
4. now run new release
5. check logs on the build agent, you will find the JSON path "IAMINVALID" in the logs

Can you replicate this?

**Comment by madhurig** [comment]
@JKennedy24 : There are 2 places you can edit which might be causing the confusion.

1. Edit the "Release definition". If you click on the "Edit" button at this level, it will change the "Release Definition" and will apply to all new "Releases"
<img width="375" alt="releasedefinition" src="https://user-images.githubusercontent.com/3269636/27187874-5b7c7f72-51ba-11e7-927b-01ac5aa7eabf.png">

2. Edit a "Release". If you make changes on a "Release", it will be saved for new "Deployments" of the same "Release" but not apply if you queue a new "Release".
<img width="634" alt="release" src="https://user-images.githubusercontent.com/3269636/27187908-7750e65c-51ba-11e7-8f07-6060376ccd6d.png">

I suspect you are editing a "Release" and queuing a new "Release" on the definition which is still pointing to the invalid JSON path. I agree this is very confusing, I have done the same several times.

Thanks,
Madhuri

**Comment by JKennedy24** [comment]
This issue seems to work now. Thanks for your help on this one. Was probably a red herring
