### ISSUE TITLE
No logging information displayed in VSO on error

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/google-play-vsts-extension#62]
If an error occurs all that is shown in VSO is 

> ##[error]{"cause":{},"isOperational":true}

You need to look at agent log files to find out whats gone wrong. Not possible if youre using a virtual machine in VS cloud

**Comment by madhurig** [comment]
@JKennedy24 : Thank you for reporting the issue, this was a regression introduced in [a recent commit](https://github.com/Microsoft/google-play-vsts-extension/commit/471b2c718034b3bccf367747076d08e2ba9b8220). I am working on an update with the fix.

Regards,
Madhuri

**Comment by madhurig** [comment]
@JKennedy24 : Fix has been released to the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.google-play)

**Comment by JKennedy24** [comment]
thanks @madhurig. Do these extensions update automatically or do I need to do something to update my extension?

**Comment by madhurig** [comment]
The extension update is triggered when a build using it is run or if the tasks editor is opened up in the UI. Please not the update happens asynchronously, so you might have to queue a 2nd build after a couple of minutes to get the new version. 

Thanks,
Madhuri

**Comment by JKennedy24** [comment]
Ok thanks for you help. I will test this out and get back to you. Hopefully this may clear up a few of the other issues I was seeing

**Comment by JKennedy24** [comment]
This issue is now fixed. Thanks!
