### ISSUE TITLE
Supplying Path to text file containing release notes breaks release

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/google-play-vsts-extension#64]
If you supply a Path to a text file which contains release notes it breaks the task when releasing to Alpha

**Comment by madhurig** [comment]
@JKennedy24 : Can you provide more details on how "it breaks the task"? Please share debug logs here or email me at madhurig at microsoft.com.

Thanks,
Madhuri

**Comment by JKennedy24** [comment]
Hi madhurig, thanks for getting back to me. I will try this again next release and grab the logs and update you

**Comment by JKennedy24** [comment]
this is the error I am getting when supplying a `Release Notes` file

> 2017-06-29T15:56:58.4665530Z ##[error]Error: Error in edits.commitAsync(): {"cause":{"code":403,"errors":[{"domain":"androidpublisher","reason":"apkRecentChangesAddedForMissingLanguage","message":"Tried to set recent changes text for APK version 7 for language en-US. Language is not associated with the app."}]},"isOperational":true,"code":403,"errors":[{"domain":"androidpublisher","reason":"apkRecentChangesAddedForMissingLanguage","message":"Tried to set recent changes text for APK version 7 for language en-US. Language is not associated with the app."}]}

**Comment by madhurig** [comment]
@JKennedy24 : "Release notes" is a convenience field provided to update change log for en-US. If your app's main language is different or if you have multiple languages associated with your app, please provide the change logs in the metadata format provided in the readme.

Metadata Root Directory (String, Required if visible) - Root directory for metadata related files. Becomes available after enabling the Update Metadata option. Expects a format similar to fastlane’s supply tool which is summarized below:

$(Specified Directory)
   └ $(languageCodes)
     ├ full_description.txt
     ├ short_description.txt
     ├ title.txt
     ├ video.txt
     ├ images
     |  ├ featureGraphic.png    || featureGraphic.jpg   || featureGraphic.jpeg
     |  ├ icon.png              || icon.jpg             || icon.jpeg
     |  ├ promoGraphic.png      || promoGraphic.jpg     || promoGraphic.jpeg
     |  ├ tvBanner.png          || tvBanner.jpg         || tvBanner.jpeg
     |  ├ phoneScreenshots
     |  |  └ *.png || *.jpg || *.jpeg
     |  ├ sevenInchScreenshots
     |  |  └ *.png || *.jpg || *.jpeg
     |  ├ tenInchScreenshots
     |  |  └ *.png || *.jpg || *.jpeg
     |  ├ tvScreenshots
     |  |  └ *.png || *.jpg || *.jpeg
     |  └ wearScreenshots
     |     └ *.png || *.jpg || *.jpeg
     └ changelogs
       └ $(versioncodes).txt

Thanks,
Madhuri

**Comment by JKennedy24** [comment]
Thanks for the confirmation Madhuri. I will now close this off
