### ISSUE TITLE
Unhelpful error message during Deploy to Alpha

### ISSUE THREAD

**Issue by justinmwarner** [Microsoft/google-play-vsts-extension#68]
Hello,

I've been trying to get this extension to work and am having some issues.  I've resolved about five issues thanks to the helpful error messages.

Now however, I've come across a seemingly random error message:

> 2017-06-21T00:38:13.2441818Z ##[debug]Error: APK has invalid or missing signing information for some files.

I was wondering if this is a known issue and what the solution is or if it's possible to put more verbose logging in to track down the issue.

Here's the full output:

> 2017-06-21T01:03:42.8008920Z ##[debug]Evaluating condition for step: 'Release $(build.sourcesdirectory)/**/app-release.apk to alpha'
> 2017-06-21T01:03:42.8008920Z ##[debug]Evaluating: succeeded()
> 2017-06-21T01:03:42.8008920Z ##[debug]Evaluating succeeded:
> 2017-06-21T01:03:42.8008920Z ##[debug]=> (Boolean) True
> 2017-06-21T01:03:42.8008920Z ##[debug]Expanded: True
> 2017-06-21T01:03:42.8008920Z ##[debug]Result: True
> 2017-06-21T01:03:42.8008920Z ##[section]Starting: Release $(build.sourcesdirectory)/**/app-release.apk to alpha
> 2017-06-21T01:03:42.8018921Z ==============================================================================
> 2017-06-21T01:03:42.8018921Z Task         : Google Play - Release
> 2017-06-21T01:03:42.8018921Z Description  : Release an app to the Google Play Store
> 2017-06-21T01:03:42.8018921Z Version      : 1.119.0
> 2017-06-21T01:03:42.8018921Z Author       : Microsoft Corporation
> 2017-06-21T01:03:42.8018921Z Help         : 
> 2017-06-21T01:03:42.8018921Z ==============================================================================
> 2017-06-21T01:03:43.0328916Z ##[debug]agent.workFolder=d:\a
> 2017-06-21T01:03:43.0328916Z ##[debug]loading inputs and endpoints
> 2017-06-21T01:03:43.2268925Z ##[debug]loading ENDPOINT_AUTH_28c6fde1-1111-4338-8108-da6fd2151462
> 2017-06-21T01:03:43.2278923Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_28c6fde1-1111-4338-8108-da6fd2151462_PASSWORD
> 2017-06-21T01:03:43.4188921Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_28c6fde1-1111-4338-8108-da6fd2151462_USERNAME
> 2017-06-21T01:03:43.4198925Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
> 2017-06-21T01:03:43.4198925Z ##[debug]loading ENDPOINT_AUTH_SCHEME_28c6fde1-1111-4338-8108-da6fd2151462
> 2017-06-21T01:03:43.4198925Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
> 2017-06-21T01:03:43.4198925Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
> 2017-06-21T01:03:43.4198925Z ##[debug]loading INPUT_APKFILE
> 2017-06-21T01:03:43.4198925Z ##[debug]loading INPUT_AUTHTYPE
> 2017-06-21T01:03:43.4198925Z ##[debug]loading INPUT_CHANGELOGFILE
> 2017-06-21T01:03:43.4198925Z ##[debug]loading INPUT_LANGUAGECODE
> 2017-06-21T01:03:43.4198925Z ##[debug]loading INPUT_METADATAROOTPATH
> 2017-06-21T01:03:43.4208918Z ##[debug]loading INPUT_SERVICEACCOUNTKEY
> 2017-06-21T01:03:43.4208918Z ##[debug]loading INPUT_SERVICEENDPOINT
> 2017-06-21T01:03:43.4208918Z ##[debug]loading INPUT_SHOULDATTACHMETADATA
> 2017-06-21T01:03:43.4208918Z ##[debug]loading INPUT_SHOULDUPLOADAPKS
> 2017-06-21T01:03:43.4208918Z ##[debug]loading INPUT_TRACK
> 2017-06-21T01:03:43.4208918Z ##[debug]loading INPUT_VERSIONCODEFILTERTYPE
> 2017-06-21T01:03:43.4208918Z ##[debug]loaded 18
> 2017-06-21T01:03:43.6228919Z ##[debug]check path : d:\a\_tasks\GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27\1.119.0\task.json
> 2017-06-21T01:03:43.6228919Z ##[debug]set resource file to: d:\a\_tasks\GooglePlayRelease_8cf7cac0-620b-11e5-b4cf-8565e60f4d27\1.119.0\task.json
> 2017-06-21T01:03:43.7318922Z ##[debug]system.culture=en-US
> 2017-06-21T01:03:43.7318922Z ##[debug]Prepare task inputs.
> 2017-06-21T01:03:43.7318922Z ##[debug]authType=ServiceEndpoint
> 2017-06-21T01:03:43.7318922Z ##[debug]serviceEndpoint=28c6fde1-1111-4338-8108-da6fd2151462
> 2017-06-21T01:03:43.7318922Z 28c6fde1-1111-4338-8108-da6fd2151462 exists true
> 2017-06-21T01:03:43.7318922Z ##[debug]28c6fde1-1111-4338-8108-da6fd2151462 exists true
> 2017-06-21T01:03:43.7318922Z ##[debug]apkFile=d:\a\1\s\**\app-release.apk
> 2017-06-21T01:03:43.7328923Z ##[debug]Main APK pattern: d:\a\1\s\**\app-release.apk
> 2017-06-21T01:03:44.3638924Z ##[debug]check path : d:/a/1/s/app/app-release.apk
> 2017-06-21T01:03:44.4068919Z Found main APK to upload: d:/a/1/s/app/app-release.apk (version code 1)
> 2017-06-21T01:03:44.4068919Z ##[debug]    Found the main APK file: d:/a/1/s/app/app-release.apk (version code 1).
> 2017-06-21T01:03:44.4068919Z ##[debug]additionalApks=null
> 2017-06-21T01:03:44.4068919Z ##[debug]versionCodeFilterType=all
> 2017-06-21T01:03:44.4068919Z ##[debug]track=alpha
> 2017-06-21T01:03:44.4068919Z ##[debug]userFraction=null
> 2017-06-21T01:03:44.4068919Z ##[debug]shouldAttachMetadata=false
> 2017-06-21T01:03:44.4068919Z ##[debug]shouldUploadApks=true
> 2017-06-21T01:03:44.4068919Z ##[debug]changelogFile=d:\a\1\s
> 2017-06-21T01:03:44.4078924Z ##[debug]languageCode=en-US
> 2017-06-21T01:03:44.4078924Z ##[debug]Getting a package name from d:/a/1/s/app/app-release.apk
> 2017-06-21T01:03:44.4378922Z ##[debug]Successfully extracted the package name com.awesomeness.souschef2 from the APK d:/a/1/s/app/app-release.apk
> 2017-06-21T01:03:44.4388920Z ##[debug]Updating Global Parameter packageName to "com.awesomeness.souschef2"
> 2017-06-21T01:03:44.4388920Z ##[debug]   ... updated.
> 2017-06-21T01:03:44.4398926Z ##[debug]Initializing JWT.
> 2017-06-21T01:03:44.4398926Z ##[debug]Initializing Google Play publisher API.
> 2017-06-21T01:03:44.4558926Z ##[debug]Authorize JWT.
> 2017-06-21T01:03:44.5958922Z Authenticated with Google Play and getting new edit 
> 2017-06-21T01:03:44.5958922Z ##[debug]Creating a new edit transaction in Google Play.
> 2017-06-21T01:03:44.6068925Z ##[debug]Request Parameters: {"packageName":"com.awesomeness.souschef2"}
> 2017-06-21T01:03:44.8158936Z ##[debug]Updating Global Parameter editId to "01836179824824654883"
> 2017-06-21T01:03:44.8158936Z ##[debug]   ... updated.
> 2017-06-21T01:03:44.8158936Z ##[debug]Uploading 1 APK(s).
> 2017-06-21T01:03:44.8158936Z ##[debug]Uploading APK d:/a/1/s/app/app-release.apk
> 2017-06-21T01:03:44.8168927Z ##[debug]Request Parameters: {"packageName":"com.awesomeness.souschef2","media":{"body":{"_readableState":{"objectMode":false,"highWaterMark":65536,"buffer":{"head":null,"tail":null,"length":0},"length":0,"pipes":null,"pipesCount":0,"flowing":null,"ended":false,"endEmitted":false,"reading":false,"sync":true,"needReadable":false,"emittedReadable":false,"readableListening":false,"resumeScheduled":false,"defaultEncoding":"utf8","ranOut":false,"awaitDrain":0,"readingMore":false,"decoder":null,"encoding":null},"readable":true,"domain":null,"_events":{},"_eventsCount":1,"path":"d:/a/1/s/app/app-release.apk","fd":null,"flags":"r","mode":438,"autoClose":true,"bytesRead":0},"mimeType":"application/vnd.android.package-archive"}}
> 2017-06-21T01:03:46.2068904Z ##[debug]Failed to upload the APK d:/a/1/s/app/app-release.apk
> 2017-06-21T01:03:46.2078911Z ##[debug]Error: APK has invalid or missing signing information for some files.
> 2017-06-21T01:03:46.2078911Z ##[debug]task result: Failed
> 2017-06-21T01:03:46.2128923Z ##[error]Error: Failed to upload the APK d:/a/1/s/app/app-release.apk.
> 2017-06-21T01:03:46.2128923Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Failed to upload the APK d:/a/1/s/app/app-release.apk.
> 2017-06-21T01:03:46.2128923Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Failed to upload the APK d:/a/1/s/app/app-release.apk.
> 2017-06-21T01:03:46.2168915Z ##[section]Finishing: Release $(build.sourcesdirectory)/**/app-release.apk to alpha
>

**Comment by madhurig** [comment]
@justinmwarner : That is the error the task gets back from Google Play. As the error indicates you will need to check if the APK is signed correctly. Have you tried uploading the APK via the Google Developer Console? 

We have a VSTS task to help sign and zip align your APKs during the build process: https://www.visualstudio.com/en-us/docs/build/steps/build/android-signing

Thanks,
Madhuri

**Comment by madhurig** [comment]
@justinmwarner : Are you still encountering this issue? Did signing the APK help?

**Comment by justinmwarner** [comment]
@madhurig signing did help.  Thanks for getting back to me. I figured this out afterwards and forgot to update here.
