### ISSUE TITLE
Promoting from Alpha fails

### ISSUE THREAD

**Issue by JKennedy24** [Microsoft/google-play-vsts-extension#73]
Error is:

> Error: Rollout user fraction must be greater than 0.0 and less than 1.0

I would like Rollout fraction to be 100% so I have tried the following values:

1.0 - failed
blank - failed

I'm guessing 0.99 would work, but obviously this would mean it would only go to 99% of my users

**Comment by AdamEssenmacher** [comment]
Instead of using the "Increase Rollout" task, use the "Promote" task using "Rollout" as your Source Track and "Production" as your Destination Track.

**Comment by JKennedy24** [comment]
@AdamEssenmacher  I've just noticed that it has `production` as a destination track.

Does this sound correct:
Source Track: `Alpha` 
Destination Track: `Production`

Or does the Source Track need to be `Rollout`?

**Comment by AdamEssenmacher** [comment]
I'm not sure. I'm having trouble with the 'Increase Rollout' task myself. I'd try "Rollout" as the source track first and see what happens. I'd be interested to know what ends up working for you!

**Comment by JKennedy24** [comment]
@AdamEssenmacher  Thanks for the info. I'll try it as `Alpha` to `Production` at the moment.

I'm guessing `Rollout` to `Production` is to be used when you have already set `50% Rollout` and now want to go complete `Rollout`.

I'll close this issue and re-open a seperate one if this doesnt work after our next release cycle
