### ISSUE TITLE
Getting 403 error when publish app to production

### ISSUE THREAD

**Issue by rubeonline** [Microsoft/google-play-vsts-extension#79]
Hi,

im getting this error when im publishing to production:

`Error: Error in edits.commitAsync(): {"cause":{"code":403,"errors":[{"domain":"androidpublisher","reason":"multiApkShadowedActiveApk","message":"Version 2017451900 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."}]},"isOperational":true,"code":403,"errors":[{"domain":"androidpublisher","reason":"multiApkShadowedActiveApk","message":"Version 2017451900 of this app can not be downloaded by any devices as they will all receive APKs with higher version codes."}]}`

`System.Exception: Task GooglePlayRelease failed. This caused the job to fail. Look at the logs for the task for more details.
at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.Run(IJobContext jobContext, IJobRequest job, IJobExtension jobExtension, CancellationTokenSource tokenSource)`

My version number whish is going to be uploaded is higher than the uploaded version number. I checked the checkbox with Update APK.

The same step to beta does work like a charm. 

Any idea?  I have installed the current version.

**Comment by rubeonline** [comment]
Version number in beta:
2017441800

Version number in production:
2017432390

Version number to upload to production:
2017451900

**Comment by madhurig** [comment]
@rubeonline: GooglePlay requires the version number in beta to be higher than production, which is what this error indicates. From the developer console, you can deactivate the Beta and then upload to production but we don't allow that via the VSTS task today automatically. When you upload this version from the google developer console to production manually, don't you see this message?

The way to do this is to upload the higher version to Beta and then promote to Production.

**Comment by rubeonline** [comment]
@madhurig: Thanks a lot. Now i understand the process at google. The message in the build output was not so helpfull.

**Comment by madhurig** [comment]
@rubeonline : I agree on the error message. In the VSTS task we are just showing the error we get back from GooglePlay. We can definitely improve that. Thanks for the feedback!
