### ISSUE TITLE
noPrimarilyChildDirectedStatus error, although status is set!

### ISSUE THREAD

**Issue by SteveKennedy** [Microsoft/google-play-vsts-extension#82]
I have triple checked my Google developer console, to ensure that my app is set to set to NO - that my app is not primarily directed toward children (under age 13). It has been set that way for a long time (weeks/months). But when I run the VSTS release with this extension, I still get the following error.  

> Error: Error in edits.commitAsync(): {"cause":{"code":403,"errors":[{"domain":"androidpublisher","reason":"noPrimarilyChildDirectedStatus","message":"**You are required to indicate if your app is primarily directed towards children in the pricing and distribution section of the Play Console.**"}]},"isOperational":true,"code":403,"errors":[{"domain":"androidpublisher","reason":"noPrimarilyChildDirectedStatus","message":"You are required to indicate if your app is primarily directed towards children in the pricing and distribution section of the Play Console."}]}

![image](https://user-images.githubusercontent.com/12101125/31956871-70768d14-b8b2-11e7-8004-f6ed9e13e062.png)

**Comment by SteveKennedy** [comment]
My bad. Please close this. I actually had TWO different google play console accounts, with the same named APP on each of them.  Once was approved/answered, and was was actually not set.

**Comment by AlexRukhlin** [comment]
By the author's request.
