### ISSUE TITLE
Failed to create a new edit transaction for the package. Error: null

### ISSUE THREAD

**Issue by noChamp** [Microsoft/google-play-vsts-extension#88]
hi
I am using Goggle Play - Release to release strait to Beta channel.
The process fails.
I am getting that the error is null........
Please help.....

Here are the full logs (system.debug=true):

Found main APK to upload: /Users/vsts/agent/2.126.0/work/1/s/platforms/android/build/outputs/apk/android-release.apk (version code 307030)
Found the main APK file: /Users/vsts/agent/2.126.0/work/1/s/platforms/android/build/outputs/apk/android-release.apk (version code 307030).
additionalApks=null
versionCodeFilterType=all
track=beta
userFraction=null
shouldAttachMetadata=false
shouldUploadApks=true
changelogFile=/Users/vsts/agent/2.126.0/work/1/s
languageCode=en-US
Getting a package name from /Users/vsts/agent/2.126.0/work/1/s/platforms/android/build/outputs/apk/android-release.apk
Updating Global Parameter packageName to "com.diamining.hybrid.Barbi"
... updated.
Initializing JWT.
Initializing Google Play publisher API.
Authorize JWT.
Authenticated with Google Play and getting new edit 
Creating a new edit transaction in Google Play.
Request Parameters: {"packageName":"com.diamining.hybrid.Barbi"}
Failed to create a new edit transaction for the package com.diamining.hybrid.Barbi.
Error: null
task result: Failed
Error: Failed to create a new edit transaction for the package com.diamining.hybrid.Barbi. Failed with message: Error: null. See log for details.
Processed: ##vso[task.issue type=error;]Error: Failed to create a new edit transaction for the package com.diamining.hybrid.Barbi. Failed with message: Error: null. See log for details.
Processed: ##vso[task.complete result=Failed;]Error: Failed to create a new edit transaction for the package com.diamining.hybrid.Barbi. Failed with message: Error: null. See log for details.
******************************************************************************
Finishing: Release to beta
******************************************************************************

**Comment by noChamp** [comment]
I am using 'JSON Auth File' method, and authentication succeded.
from the logs "Authenticated with Google Play..."
so what can be the problem?

**Comment by lkillgore** [comment]
Hi @noChamp!  The 'null' message means that we weren't given an error message from google's API. 
 They might, however, give you a better message if you call it directly.  Could you please try something out for me?  Could you try using this site to try the step that's failing manually?https://developers.google.com/apis-explorer/#search/androidpublisher/androidpublisher/v2/androidpublisher.edits.insert (I think all you have to do is type in your package name and authenticate with your google play account.)

Assuming the problem isn't authentication, this should give a more detailed explanation of what's going wrong.

**Comment by noChamp** [comment]
thanks for helping!
I an using it and I get "The project id used to call the Google Play Developer API has not been linked in the Google Play Developer Console"

**Comment by lkillgore** [comment]
Hi @noChamp!  Yes, I have seen this message before!  This suggestion from stackoverflow should get things working: https://stackoverflow.com/a/25655897.  Please let me know if that fixes things for you.

**Comment by noChamp** [comment]
hi
thanks a lot for your continued help!
its much appreciated!
I did everything listed there and it still didn't work, so I approached Google Support and they fixed it on their side
thanks again
M
